
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  YahooAccount: 'YahooAccount',
  League: 'League',
  Team: 'Team',
  TeamStanding: 'TeamStanding',
  Player: 'Player',
  RosterEntry: 'RosterEntry',
  PlayerValue: 'PlayerValue',
  DraftPickValue: 'DraftPickValue',
  TeamDraftPick: 'TeamDraftPick',
  PlayerStat: 'PlayerStat'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const YahooAccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  yahooUserId: 'yahooUserId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type YahooAccountScalarFieldEnum = (typeof YahooAccountScalarFieldEnum)[keyof typeof YahooAccountScalarFieldEnum]


export const LeagueScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  leagueKey: 'leagueKey',
  name: 'name',
  season: 'season',
  sport: 'sport',
  teamCount: 'teamCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LeagueScalarFieldEnum = (typeof LeagueScalarFieldEnum)[keyof typeof LeagueScalarFieldEnum]


export const TeamScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  leagueId: 'leagueId',
  teamKey: 'teamKey',
  name: 'name',
  managerName: 'managerName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamScalarFieldEnum = (typeof TeamScalarFieldEnum)[keyof typeof TeamScalarFieldEnum]


export const TeamStandingScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  wins: 'wins',
  losses: 'losses',
  ties: 'ties',
  pointsFor: 'pointsFor',
  pointsAgainst: 'pointsAgainst',
  rank: 'rank',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamStandingScalarFieldEnum = (typeof TeamStandingScalarFieldEnum)[keyof typeof TeamStandingScalarFieldEnum]


export const PlayerScalarFieldEnum = {
  id: 'id',
  playerKey: 'playerKey',
  name: 'name',
  teamAbbr: 'teamAbbr',
  positions: 'positions',
  primaryPosition: 'primaryPosition',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlayerScalarFieldEnum = (typeof PlayerScalarFieldEnum)[keyof typeof PlayerScalarFieldEnum]


export const RosterEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  leagueId: 'leagueId',
  teamId: 'teamId',
  playerId: 'playerId',
  yahooPosition: 'yahooPosition',
  isBench: 'isBench',
  isInjuredList: 'isInjuredList',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RosterEntryScalarFieldEnum = (typeof RosterEntryScalarFieldEnum)[keyof typeof RosterEntryScalarFieldEnum]


export const PlayerValueScalarFieldEnum = {
  id: 'id',
  playerId: 'playerId',
  leagueId: 'leagueId',
  score: 'score',
  breakdown: 'breakdown',
  updatedAt: 'updatedAt'
} as const

export type PlayerValueScalarFieldEnum = (typeof PlayerValueScalarFieldEnum)[keyof typeof PlayerValueScalarFieldEnum]


export const DraftPickValueScalarFieldEnum = {
  id: 'id',
  leagueId: 'leagueId',
  round: 'round',
  score: 'score',
  updatedAt: 'updatedAt'
} as const

export type DraftPickValueScalarFieldEnum = (typeof DraftPickValueScalarFieldEnum)[keyof typeof DraftPickValueScalarFieldEnum]


export const TeamDraftPickScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  leagueId: 'leagueId',
  round: 'round',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamDraftPickScalarFieldEnum = (typeof TeamDraftPickScalarFieldEnum)[keyof typeof TeamDraftPickScalarFieldEnum]


export const PlayerStatScalarFieldEnum = {
  id: 'id',
  playerId: 'playerId',
  leagueId: 'leagueId',
  statId: 'statId',
  statName: 'statName',
  value: 'value',
  updatedAt: 'updatedAt'
} as const

export type PlayerStatScalarFieldEnum = (typeof PlayerStatScalarFieldEnum)[keyof typeof PlayerStatScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

