
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `League` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model League
 * 
 */
export type LeagueModel = runtime.Types.Result.DefaultSelection<Prisma.$LeaguePayload>

export type AggregateLeague = {
  _count: LeagueCountAggregateOutputType | null
  _avg: LeagueAvgAggregateOutputType | null
  _sum: LeagueSumAggregateOutputType | null
  _min: LeagueMinAggregateOutputType | null
  _max: LeagueMaxAggregateOutputType | null
}

export type LeagueAvgAggregateOutputType = {
  teamCount: number | null
}

export type LeagueSumAggregateOutputType = {
  teamCount: number | null
}

export type LeagueMinAggregateOutputType = {
  id: string | null
  userId: string | null
  leagueKey: string | null
  name: string | null
  season: string | null
  sport: string | null
  teamCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LeagueMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  leagueKey: string | null
  name: string | null
  season: string | null
  sport: string | null
  teamCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LeagueCountAggregateOutputType = {
  id: number
  userId: number
  leagueKey: number
  name: number
  season: number
  sport: number
  teamCount: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LeagueAvgAggregateInputType = {
  teamCount?: true
}

export type LeagueSumAggregateInputType = {
  teamCount?: true
}

export type LeagueMinAggregateInputType = {
  id?: true
  userId?: true
  leagueKey?: true
  name?: true
  season?: true
  sport?: true
  teamCount?: true
  createdAt?: true
  updatedAt?: true
}

export type LeagueMaxAggregateInputType = {
  id?: true
  userId?: true
  leagueKey?: true
  name?: true
  season?: true
  sport?: true
  teamCount?: true
  createdAt?: true
  updatedAt?: true
}

export type LeagueCountAggregateInputType = {
  id?: true
  userId?: true
  leagueKey?: true
  name?: true
  season?: true
  sport?: true
  teamCount?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LeagueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which League to aggregate.
   */
  where?: Prisma.LeagueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leagues to fetch.
   */
  orderBy?: Prisma.LeagueOrderByWithRelationInput | Prisma.LeagueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeagueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leagues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leagues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Leagues
  **/
  _count?: true | LeagueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LeagueAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LeagueSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeagueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeagueMaxAggregateInputType
}

export type GetLeagueAggregateType<T extends LeagueAggregateArgs> = {
      [P in keyof T & keyof AggregateLeague]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLeague[P]>
    : Prisma.GetScalarType<T[P], AggregateLeague[P]>
}




export type LeagueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeagueWhereInput
  orderBy?: Prisma.LeagueOrderByWithAggregationInput | Prisma.LeagueOrderByWithAggregationInput[]
  by: Prisma.LeagueScalarFieldEnum[] | Prisma.LeagueScalarFieldEnum
  having?: Prisma.LeagueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeagueCountAggregateInputType | true
  _avg?: LeagueAvgAggregateInputType
  _sum?: LeagueSumAggregateInputType
  _min?: LeagueMinAggregateInputType
  _max?: LeagueMaxAggregateInputType
}

export type LeagueGroupByOutputType = {
  id: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount: number | null
  createdAt: Date
  updatedAt: Date
  _count: LeagueCountAggregateOutputType | null
  _avg: LeagueAvgAggregateOutputType | null
  _sum: LeagueSumAggregateOutputType | null
  _min: LeagueMinAggregateOutputType | null
  _max: LeagueMaxAggregateOutputType | null
}

type GetLeagueGroupByPayload<T extends LeagueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeagueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeagueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeagueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeagueGroupByOutputType[P]>
      }
    >
  >



export type LeagueWhereInput = {
  AND?: Prisma.LeagueWhereInput | Prisma.LeagueWhereInput[]
  OR?: Prisma.LeagueWhereInput[]
  NOT?: Prisma.LeagueWhereInput | Prisma.LeagueWhereInput[]
  id?: Prisma.StringFilter<"League"> | string
  userId?: Prisma.StringFilter<"League"> | string
  leagueKey?: Prisma.StringFilter<"League"> | string
  name?: Prisma.StringFilter<"League"> | string
  season?: Prisma.StringFilter<"League"> | string
  sport?: Prisma.StringFilter<"League"> | string
  teamCount?: Prisma.IntNullableFilter<"League"> | number | null
  createdAt?: Prisma.DateTimeFilter<"League"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"League"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  teams?: Prisma.TeamListRelationFilter
  rosterEntries?: Prisma.RosterEntryListRelationFilter
  playerValues?: Prisma.PlayerValueListRelationFilter
  draftPickValues?: Prisma.DraftPickValueListRelationFilter
  teamDraftPicks?: Prisma.TeamDraftPickListRelationFilter
  playerStats?: Prisma.PlayerStatListRelationFilter
}

export type LeagueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  season?: Prisma.SortOrder
  sport?: Prisma.SortOrder
  teamCount?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  teams?: Prisma.TeamOrderByRelationAggregateInput
  rosterEntries?: Prisma.RosterEntryOrderByRelationAggregateInput
  playerValues?: Prisma.PlayerValueOrderByRelationAggregateInput
  draftPickValues?: Prisma.DraftPickValueOrderByRelationAggregateInput
  teamDraftPicks?: Prisma.TeamDraftPickOrderByRelationAggregateInput
  playerStats?: Prisma.PlayerStatOrderByRelationAggregateInput
}

export type LeagueWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_leagueKey?: Prisma.LeagueUserIdLeagueKeyCompoundUniqueInput
  AND?: Prisma.LeagueWhereInput | Prisma.LeagueWhereInput[]
  OR?: Prisma.LeagueWhereInput[]
  NOT?: Prisma.LeagueWhereInput | Prisma.LeagueWhereInput[]
  userId?: Prisma.StringFilter<"League"> | string
  leagueKey?: Prisma.StringFilter<"League"> | string
  name?: Prisma.StringFilter<"League"> | string
  season?: Prisma.StringFilter<"League"> | string
  sport?: Prisma.StringFilter<"League"> | string
  teamCount?: Prisma.IntNullableFilter<"League"> | number | null
  createdAt?: Prisma.DateTimeFilter<"League"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"League"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  teams?: Prisma.TeamListRelationFilter
  rosterEntries?: Prisma.RosterEntryListRelationFilter
  playerValues?: Prisma.PlayerValueListRelationFilter
  draftPickValues?: Prisma.DraftPickValueListRelationFilter
  teamDraftPicks?: Prisma.TeamDraftPickListRelationFilter
  playerStats?: Prisma.PlayerStatListRelationFilter
}, "id" | "userId_leagueKey">

export type LeagueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  season?: Prisma.SortOrder
  sport?: Prisma.SortOrder
  teamCount?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LeagueCountOrderByAggregateInput
  _avg?: Prisma.LeagueAvgOrderByAggregateInput
  _max?: Prisma.LeagueMaxOrderByAggregateInput
  _min?: Prisma.LeagueMinOrderByAggregateInput
  _sum?: Prisma.LeagueSumOrderByAggregateInput
}

export type LeagueScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeagueScalarWhereWithAggregatesInput | Prisma.LeagueScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeagueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeagueScalarWhereWithAggregatesInput | Prisma.LeagueScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"League"> | string
  userId?: Prisma.StringWithAggregatesFilter<"League"> | string
  leagueKey?: Prisma.StringWithAggregatesFilter<"League"> | string
  name?: Prisma.StringWithAggregatesFilter<"League"> | string
  season?: Prisma.StringWithAggregatesFilter<"League"> | string
  sport?: Prisma.StringWithAggregatesFilter<"League"> | string
  teamCount?: Prisma.IntNullableWithAggregatesFilter<"League"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"League"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"League"> | Date | string
}

export type LeagueCreateInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateManyInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeagueUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeagueUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeagueListRelationFilter = {
  every?: Prisma.LeagueWhereInput
  some?: Prisma.LeagueWhereInput
  none?: Prisma.LeagueWhereInput
}

export type LeagueOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeagueUserIdLeagueKeyCompoundUniqueInput = {
  userId: string
  leagueKey: string
}

export type LeagueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  season?: Prisma.SortOrder
  sport?: Prisma.SortOrder
  teamCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeagueAvgOrderByAggregateInput = {
  teamCount?: Prisma.SortOrder
}

export type LeagueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  season?: Prisma.SortOrder
  sport?: Prisma.SortOrder
  teamCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeagueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  season?: Prisma.SortOrder
  sport?: Prisma.SortOrder
  teamCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeagueSumOrderByAggregateInput = {
  teamCount?: Prisma.SortOrder
}

export type LeagueScalarRelationFilter = {
  is?: Prisma.LeagueWhereInput
  isNot?: Prisma.LeagueWhereInput
}

export type LeagueCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutUserInput, Prisma.LeagueUncheckedCreateWithoutUserInput> | Prisma.LeagueCreateWithoutUserInput[] | Prisma.LeagueUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutUserInput | Prisma.LeagueCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LeagueCreateManyUserInputEnvelope
  connect?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
}

export type LeagueUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutUserInput, Prisma.LeagueUncheckedCreateWithoutUserInput> | Prisma.LeagueCreateWithoutUserInput[] | Prisma.LeagueUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutUserInput | Prisma.LeagueCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LeagueCreateManyUserInputEnvelope
  connect?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
}

export type LeagueUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutUserInput, Prisma.LeagueUncheckedCreateWithoutUserInput> | Prisma.LeagueCreateWithoutUserInput[] | Prisma.LeagueUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutUserInput | Prisma.LeagueCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LeagueUpsertWithWhereUniqueWithoutUserInput | Prisma.LeagueUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LeagueCreateManyUserInputEnvelope
  set?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  disconnect?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  delete?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  connect?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  update?: Prisma.LeagueUpdateWithWhereUniqueWithoutUserInput | Prisma.LeagueUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LeagueUpdateManyWithWhereWithoutUserInput | Prisma.LeagueUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LeagueScalarWhereInput | Prisma.LeagueScalarWhereInput[]
}

export type LeagueUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutUserInput, Prisma.LeagueUncheckedCreateWithoutUserInput> | Prisma.LeagueCreateWithoutUserInput[] | Prisma.LeagueUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutUserInput | Prisma.LeagueCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LeagueUpsertWithWhereUniqueWithoutUserInput | Prisma.LeagueUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LeagueCreateManyUserInputEnvelope
  set?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  disconnect?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  delete?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  connect?: Prisma.LeagueWhereUniqueInput | Prisma.LeagueWhereUniqueInput[]
  update?: Prisma.LeagueUpdateWithWhereUniqueWithoutUserInput | Prisma.LeagueUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LeagueUpdateManyWithWhereWithoutUserInput | Prisma.LeagueUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LeagueScalarWhereInput | Prisma.LeagueScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type LeagueCreateNestedOneWithoutTeamsInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutTeamsInput, Prisma.LeagueUncheckedCreateWithoutTeamsInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutTeamsInput
  connect?: Prisma.LeagueWhereUniqueInput
}

export type LeagueUpdateOneRequiredWithoutTeamsNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutTeamsInput, Prisma.LeagueUncheckedCreateWithoutTeamsInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutTeamsInput
  upsert?: Prisma.LeagueUpsertWithoutTeamsInput
  connect?: Prisma.LeagueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeagueUpdateToOneWithWhereWithoutTeamsInput, Prisma.LeagueUpdateWithoutTeamsInput>, Prisma.LeagueUncheckedUpdateWithoutTeamsInput>
}

export type LeagueCreateNestedOneWithoutRosterEntriesInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutRosterEntriesInput, Prisma.LeagueUncheckedCreateWithoutRosterEntriesInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutRosterEntriesInput
  connect?: Prisma.LeagueWhereUniqueInput
}

export type LeagueUpdateOneRequiredWithoutRosterEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutRosterEntriesInput, Prisma.LeagueUncheckedCreateWithoutRosterEntriesInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutRosterEntriesInput
  upsert?: Prisma.LeagueUpsertWithoutRosterEntriesInput
  connect?: Prisma.LeagueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeagueUpdateToOneWithWhereWithoutRosterEntriesInput, Prisma.LeagueUpdateWithoutRosterEntriesInput>, Prisma.LeagueUncheckedUpdateWithoutRosterEntriesInput>
}

export type LeagueCreateNestedOneWithoutPlayerValuesInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerValuesInput, Prisma.LeagueUncheckedCreateWithoutPlayerValuesInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutPlayerValuesInput
  connect?: Prisma.LeagueWhereUniqueInput
}

export type LeagueUpdateOneRequiredWithoutPlayerValuesNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerValuesInput, Prisma.LeagueUncheckedCreateWithoutPlayerValuesInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutPlayerValuesInput
  upsert?: Prisma.LeagueUpsertWithoutPlayerValuesInput
  connect?: Prisma.LeagueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeagueUpdateToOneWithWhereWithoutPlayerValuesInput, Prisma.LeagueUpdateWithoutPlayerValuesInput>, Prisma.LeagueUncheckedUpdateWithoutPlayerValuesInput>
}

export type LeagueCreateNestedOneWithoutDraftPickValuesInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutDraftPickValuesInput, Prisma.LeagueUncheckedCreateWithoutDraftPickValuesInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutDraftPickValuesInput
  connect?: Prisma.LeagueWhereUniqueInput
}

export type LeagueUpdateOneRequiredWithoutDraftPickValuesNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutDraftPickValuesInput, Prisma.LeagueUncheckedCreateWithoutDraftPickValuesInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutDraftPickValuesInput
  upsert?: Prisma.LeagueUpsertWithoutDraftPickValuesInput
  connect?: Prisma.LeagueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeagueUpdateToOneWithWhereWithoutDraftPickValuesInput, Prisma.LeagueUpdateWithoutDraftPickValuesInput>, Prisma.LeagueUncheckedUpdateWithoutDraftPickValuesInput>
}

export type LeagueCreateNestedOneWithoutTeamDraftPicksInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutTeamDraftPicksInput, Prisma.LeagueUncheckedCreateWithoutTeamDraftPicksInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutTeamDraftPicksInput
  connect?: Prisma.LeagueWhereUniqueInput
}

export type LeagueUpdateOneRequiredWithoutTeamDraftPicksNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutTeamDraftPicksInput, Prisma.LeagueUncheckedCreateWithoutTeamDraftPicksInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutTeamDraftPicksInput
  upsert?: Prisma.LeagueUpsertWithoutTeamDraftPicksInput
  connect?: Prisma.LeagueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeagueUpdateToOneWithWhereWithoutTeamDraftPicksInput, Prisma.LeagueUpdateWithoutTeamDraftPicksInput>, Prisma.LeagueUncheckedUpdateWithoutTeamDraftPicksInput>
}

export type LeagueCreateNestedOneWithoutPlayerStatsInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerStatsInput, Prisma.LeagueUncheckedCreateWithoutPlayerStatsInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutPlayerStatsInput
  connect?: Prisma.LeagueWhereUniqueInput
}

export type LeagueUpdateOneRequiredWithoutPlayerStatsNestedInput = {
  create?: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerStatsInput, Prisma.LeagueUncheckedCreateWithoutPlayerStatsInput>
  connectOrCreate?: Prisma.LeagueCreateOrConnectWithoutPlayerStatsInput
  upsert?: Prisma.LeagueUpsertWithoutPlayerStatsInput
  connect?: Prisma.LeagueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeagueUpdateToOneWithWhereWithoutPlayerStatsInput, Prisma.LeagueUpdateWithoutPlayerStatsInput>, Prisma.LeagueUncheckedUpdateWithoutPlayerStatsInput>
}

export type LeagueCreateWithoutUserInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutUserInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutUserInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutUserInput, Prisma.LeagueUncheckedCreateWithoutUserInput>
}

export type LeagueCreateManyUserInputEnvelope = {
  data: Prisma.LeagueCreateManyUserInput | Prisma.LeagueCreateManyUserInput[]
}

export type LeagueUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.LeagueWhereUniqueInput
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutUserInput, Prisma.LeagueUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutUserInput, Prisma.LeagueUncheckedCreateWithoutUserInput>
}

export type LeagueUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.LeagueWhereUniqueInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutUserInput, Prisma.LeagueUncheckedUpdateWithoutUserInput>
}

export type LeagueUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.LeagueScalarWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateManyMutationInput, Prisma.LeagueUncheckedUpdateManyWithoutUserInput>
}

export type LeagueScalarWhereInput = {
  AND?: Prisma.LeagueScalarWhereInput | Prisma.LeagueScalarWhereInput[]
  OR?: Prisma.LeagueScalarWhereInput[]
  NOT?: Prisma.LeagueScalarWhereInput | Prisma.LeagueScalarWhereInput[]
  id?: Prisma.StringFilter<"League"> | string
  userId?: Prisma.StringFilter<"League"> | string
  leagueKey?: Prisma.StringFilter<"League"> | string
  name?: Prisma.StringFilter<"League"> | string
  season?: Prisma.StringFilter<"League"> | string
  sport?: Prisma.StringFilter<"League"> | string
  teamCount?: Prisma.IntNullableFilter<"League"> | number | null
  createdAt?: Prisma.DateTimeFilter<"League"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"League"> | Date | string
}

export type LeagueCreateWithoutTeamsInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutTeamsInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutTeamsInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutTeamsInput, Prisma.LeagueUncheckedCreateWithoutTeamsInput>
}

export type LeagueUpsertWithoutTeamsInput = {
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutTeamsInput, Prisma.LeagueUncheckedUpdateWithoutTeamsInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutTeamsInput, Prisma.LeagueUncheckedCreateWithoutTeamsInput>
  where?: Prisma.LeagueWhereInput
}

export type LeagueUpdateToOneWithWhereWithoutTeamsInput = {
  where?: Prisma.LeagueWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutTeamsInput, Prisma.LeagueUncheckedUpdateWithoutTeamsInput>
}

export type LeagueUpdateWithoutTeamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutTeamsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateWithoutRosterEntriesInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutRosterEntriesInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutRosterEntriesInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutRosterEntriesInput, Prisma.LeagueUncheckedCreateWithoutRosterEntriesInput>
}

export type LeagueUpsertWithoutRosterEntriesInput = {
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutRosterEntriesInput, Prisma.LeagueUncheckedUpdateWithoutRosterEntriesInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutRosterEntriesInput, Prisma.LeagueUncheckedCreateWithoutRosterEntriesInput>
  where?: Prisma.LeagueWhereInput
}

export type LeagueUpdateToOneWithWhereWithoutRosterEntriesInput = {
  where?: Prisma.LeagueWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutRosterEntriesInput, Prisma.LeagueUncheckedUpdateWithoutRosterEntriesInput>
}

export type LeagueUpdateWithoutRosterEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutRosterEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateWithoutPlayerValuesInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutPlayerValuesInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutPlayerValuesInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerValuesInput, Prisma.LeagueUncheckedCreateWithoutPlayerValuesInput>
}

export type LeagueUpsertWithoutPlayerValuesInput = {
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutPlayerValuesInput, Prisma.LeagueUncheckedUpdateWithoutPlayerValuesInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerValuesInput, Prisma.LeagueUncheckedCreateWithoutPlayerValuesInput>
  where?: Prisma.LeagueWhereInput
}

export type LeagueUpdateToOneWithWhereWithoutPlayerValuesInput = {
  where?: Prisma.LeagueWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutPlayerValuesInput, Prisma.LeagueUncheckedUpdateWithoutPlayerValuesInput>
}

export type LeagueUpdateWithoutPlayerValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutPlayerValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateWithoutDraftPickValuesInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutDraftPickValuesInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutDraftPickValuesInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutDraftPickValuesInput, Prisma.LeagueUncheckedCreateWithoutDraftPickValuesInput>
}

export type LeagueUpsertWithoutDraftPickValuesInput = {
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutDraftPickValuesInput, Prisma.LeagueUncheckedUpdateWithoutDraftPickValuesInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutDraftPickValuesInput, Prisma.LeagueUncheckedCreateWithoutDraftPickValuesInput>
  where?: Prisma.LeagueWhereInput
}

export type LeagueUpdateToOneWithWhereWithoutDraftPickValuesInput = {
  where?: Prisma.LeagueWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutDraftPickValuesInput, Prisma.LeagueUncheckedUpdateWithoutDraftPickValuesInput>
}

export type LeagueUpdateWithoutDraftPickValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutDraftPickValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateWithoutTeamDraftPicksInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutTeamDraftPicksInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutTeamDraftPicksInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutTeamDraftPicksInput, Prisma.LeagueUncheckedCreateWithoutTeamDraftPicksInput>
}

export type LeagueUpsertWithoutTeamDraftPicksInput = {
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutTeamDraftPicksInput, Prisma.LeagueUncheckedUpdateWithoutTeamDraftPicksInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutTeamDraftPicksInput, Prisma.LeagueUncheckedCreateWithoutTeamDraftPicksInput>
  where?: Prisma.LeagueWhereInput
}

export type LeagueUpdateToOneWithWhereWithoutTeamDraftPicksInput = {
  where?: Prisma.LeagueWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutTeamDraftPicksInput, Prisma.LeagueUncheckedUpdateWithoutTeamDraftPicksInput>
}

export type LeagueUpdateWithoutTeamDraftPicksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutTeamDraftPicksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateWithoutPlayerStatsInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaguesInput
  teams?: Prisma.TeamCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickCreateNestedManyWithoutLeagueInput
}

export type LeagueUncheckedCreateWithoutPlayerStatsInput = {
  id?: string
  userId: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  teams?: Prisma.TeamUncheckedCreateNestedManyWithoutLeagueInput
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutLeagueInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutLeagueInput
  draftPickValues?: Prisma.DraftPickValueUncheckedCreateNestedManyWithoutLeagueInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedCreateNestedManyWithoutLeagueInput
}

export type LeagueCreateOrConnectWithoutPlayerStatsInput = {
  where: Prisma.LeagueWhereUniqueInput
  create: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerStatsInput, Prisma.LeagueUncheckedCreateWithoutPlayerStatsInput>
}

export type LeagueUpsertWithoutPlayerStatsInput = {
  update: Prisma.XOR<Prisma.LeagueUpdateWithoutPlayerStatsInput, Prisma.LeagueUncheckedUpdateWithoutPlayerStatsInput>
  create: Prisma.XOR<Prisma.LeagueCreateWithoutPlayerStatsInput, Prisma.LeagueUncheckedCreateWithoutPlayerStatsInput>
  where?: Prisma.LeagueWhereInput
}

export type LeagueUpdateToOneWithWhereWithoutPlayerStatsInput = {
  where?: Prisma.LeagueWhereInput
  data: Prisma.XOR<Prisma.LeagueUpdateWithoutPlayerStatsInput, Prisma.LeagueUncheckedUpdateWithoutPlayerStatsInput>
}

export type LeagueUpdateWithoutPlayerStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaguesNestedInput
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutPlayerStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueCreateManyUserInput = {
  id?: string
  leagueKey: string
  name: string
  season: string
  sport: string
  teamCount?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeagueUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  teams?: Prisma.TeamUncheckedUpdateManyWithoutLeagueNestedInput
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput
  draftPickValues?: Prisma.DraftPickValueUncheckedUpdateManyWithoutLeagueNestedInput
  teamDraftPicks?: Prisma.TeamDraftPickUncheckedUpdateManyWithoutLeagueNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutLeagueNestedInput
}

export type LeagueUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.StringFieldUpdateOperationsInput | string
  sport?: Prisma.StringFieldUpdateOperationsInput | string
  teamCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type LeagueCountOutputType
 */

export type LeagueCountOutputType = {
  teams: number
  rosterEntries: number
  playerValues: number
  draftPickValues: number
  teamDraftPicks: number
  playerStats: number
}

export type LeagueCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  teams?: boolean | LeagueCountOutputTypeCountTeamsArgs
  rosterEntries?: boolean | LeagueCountOutputTypeCountRosterEntriesArgs
  playerValues?: boolean | LeagueCountOutputTypeCountPlayerValuesArgs
  draftPickValues?: boolean | LeagueCountOutputTypeCountDraftPickValuesArgs
  teamDraftPicks?: boolean | LeagueCountOutputTypeCountTeamDraftPicksArgs
  playerStats?: boolean | LeagueCountOutputTypeCountPlayerStatsArgs
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeagueCountOutputType
   */
  select?: Prisma.LeagueCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeCountTeamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamWhereInput
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeCountRosterEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RosterEntryWhereInput
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeCountPlayerValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerValueWhereInput
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeCountDraftPickValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DraftPickValueWhereInput
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeCountTeamDraftPicksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamDraftPickWhereInput
}

/**
 * LeagueCountOutputType without action
 */
export type LeagueCountOutputTypeCountPlayerStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerStatWhereInput
}


export type LeagueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  leagueKey?: boolean
  name?: boolean
  season?: boolean
  sport?: boolean
  teamCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  teams?: boolean | Prisma.League$teamsArgs<ExtArgs>
  rosterEntries?: boolean | Prisma.League$rosterEntriesArgs<ExtArgs>
  playerValues?: boolean | Prisma.League$playerValuesArgs<ExtArgs>
  draftPickValues?: boolean | Prisma.League$draftPickValuesArgs<ExtArgs>
  teamDraftPicks?: boolean | Prisma.League$teamDraftPicksArgs<ExtArgs>
  playerStats?: boolean | Prisma.League$playerStatsArgs<ExtArgs>
  _count?: boolean | Prisma.LeagueCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["league"]>

export type LeagueSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  leagueKey?: boolean
  name?: boolean
  season?: boolean
  sport?: boolean
  teamCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["league"]>

export type LeagueSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  leagueKey?: boolean
  name?: boolean
  season?: boolean
  sport?: boolean
  teamCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["league"]>

export type LeagueSelectScalar = {
  id?: boolean
  userId?: boolean
  leagueKey?: boolean
  name?: boolean
  season?: boolean
  sport?: boolean
  teamCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LeagueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "leagueKey" | "name" | "season" | "sport" | "teamCount" | "createdAt" | "updatedAt", ExtArgs["result"]["league"]>
export type LeagueInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  teams?: boolean | Prisma.League$teamsArgs<ExtArgs>
  rosterEntries?: boolean | Prisma.League$rosterEntriesArgs<ExtArgs>
  playerValues?: boolean | Prisma.League$playerValuesArgs<ExtArgs>
  draftPickValues?: boolean | Prisma.League$draftPickValuesArgs<ExtArgs>
  teamDraftPicks?: boolean | Prisma.League$teamDraftPicksArgs<ExtArgs>
  playerStats?: boolean | Prisma.League$playerStatsArgs<ExtArgs>
  _count?: boolean | Prisma.LeagueCountOutputTypeDefaultArgs<ExtArgs>
}
export type LeagueIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LeagueIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LeaguePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "League"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    teams: Prisma.$TeamPayload<ExtArgs>[]
    rosterEntries: Prisma.$RosterEntryPayload<ExtArgs>[]
    playerValues: Prisma.$PlayerValuePayload<ExtArgs>[]
    draftPickValues: Prisma.$DraftPickValuePayload<ExtArgs>[]
    teamDraftPicks: Prisma.$TeamDraftPickPayload<ExtArgs>[]
    playerStats: Prisma.$PlayerStatPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    leagueKey: string
    name: string
    season: string
    sport: string
    teamCount: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["league"]>
  composites: {}
}

export type LeagueGetPayload<S extends boolean | null | undefined | LeagueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeaguePayload, S>

export type LeagueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeagueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeagueCountAggregateInputType | true
  }

export interface LeagueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['League'], meta: { name: 'League' } }
  /**
   * Find zero or one League that matches the filter.
   * @param {LeagueFindUniqueArgs} args - Arguments to find a League
   * @example
   * // Get one League
   * const league = await prisma.league.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeagueFindUniqueArgs>(args: Prisma.SelectSubset<T, LeagueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one League that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeagueFindUniqueOrThrowArgs} args - Arguments to find a League
   * @example
   * // Get one League
   * const league = await prisma.league.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeagueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeagueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first League that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueFindFirstArgs} args - Arguments to find a League
   * @example
   * // Get one League
   * const league = await prisma.league.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeagueFindFirstArgs>(args?: Prisma.SelectSubset<T, LeagueFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first League that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueFindFirstOrThrowArgs} args - Arguments to find a League
   * @example
   * // Get one League
   * const league = await prisma.league.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeagueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeagueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Leagues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Leagues
   * const leagues = await prisma.league.findMany()
   * 
   * // Get first 10 Leagues
   * const leagues = await prisma.league.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const leagueWithIdOnly = await prisma.league.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LeagueFindManyArgs>(args?: Prisma.SelectSubset<T, LeagueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a League.
   * @param {LeagueCreateArgs} args - Arguments to create a League.
   * @example
   * // Create one League
   * const League = await prisma.league.create({
   *   data: {
   *     // ... data to create a League
   *   }
   * })
   * 
   */
  create<T extends LeagueCreateArgs>(args: Prisma.SelectSubset<T, LeagueCreateArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Leagues.
   * @param {LeagueCreateManyArgs} args - Arguments to create many Leagues.
   * @example
   * // Create many Leagues
   * const league = await prisma.league.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeagueCreateManyArgs>(args?: Prisma.SelectSubset<T, LeagueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Leagues and returns the data saved in the database.
   * @param {LeagueCreateManyAndReturnArgs} args - Arguments to create many Leagues.
   * @example
   * // Create many Leagues
   * const league = await prisma.league.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Leagues and only return the `id`
   * const leagueWithIdOnly = await prisma.league.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeagueCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeagueCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a League.
   * @param {LeagueDeleteArgs} args - Arguments to delete one League.
   * @example
   * // Delete one League
   * const League = await prisma.league.delete({
   *   where: {
   *     // ... filter to delete one League
   *   }
   * })
   * 
   */
  delete<T extends LeagueDeleteArgs>(args: Prisma.SelectSubset<T, LeagueDeleteArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one League.
   * @param {LeagueUpdateArgs} args - Arguments to update one League.
   * @example
   * // Update one League
   * const league = await prisma.league.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeagueUpdateArgs>(args: Prisma.SelectSubset<T, LeagueUpdateArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Leagues.
   * @param {LeagueDeleteManyArgs} args - Arguments to filter Leagues to delete.
   * @example
   * // Delete a few Leagues
   * const { count } = await prisma.league.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeagueDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeagueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leagues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Leagues
   * const league = await prisma.league.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeagueUpdateManyArgs>(args: Prisma.SelectSubset<T, LeagueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leagues and returns the data updated in the database.
   * @param {LeagueUpdateManyAndReturnArgs} args - Arguments to update many Leagues.
   * @example
   * // Update many Leagues
   * const league = await prisma.league.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Leagues and only return the `id`
   * const leagueWithIdOnly = await prisma.league.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeagueUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeagueUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one League.
   * @param {LeagueUpsertArgs} args - Arguments to update or create a League.
   * @example
   * // Update or create a League
   * const league = await prisma.league.upsert({
   *   create: {
   *     // ... data to create a League
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the League we want to update
   *   }
   * })
   */
  upsert<T extends LeagueUpsertArgs>(args: Prisma.SelectSubset<T, LeagueUpsertArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Leagues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueCountArgs} args - Arguments to filter Leagues to count.
   * @example
   * // Count the number of Leagues
   * const count = await prisma.league.count({
   *   where: {
   *     // ... the filter for the Leagues we want to count
   *   }
   * })
  **/
  count<T extends LeagueCountArgs>(
    args?: Prisma.Subset<T, LeagueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeagueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a League.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeagueAggregateArgs>(args: Prisma.Subset<T, LeagueAggregateArgs>): Prisma.PrismaPromise<GetLeagueAggregateType<T>>

  /**
   * Group by League.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeagueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeagueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeagueGroupByArgs['orderBy'] }
      : { orderBy?: LeagueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeagueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeagueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the League model
 */
readonly fields: LeagueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for League.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeagueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  teams<T extends Prisma.League$teamsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.League$teamsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  rosterEntries<T extends Prisma.League$rosterEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.League$rosterEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  playerValues<T extends Prisma.League$playerValuesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.League$playerValuesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  draftPickValues<T extends Prisma.League$draftPickValuesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.League$draftPickValuesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DraftPickValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  teamDraftPicks<T extends Prisma.League$teamDraftPicksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.League$teamDraftPicksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamDraftPickPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  playerStats<T extends Prisma.League$playerStatsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.League$playerStatsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the League model
 */
export interface LeagueFieldRefs {
  readonly id: Prisma.FieldRef<"League", 'String'>
  readonly userId: Prisma.FieldRef<"League", 'String'>
  readonly leagueKey: Prisma.FieldRef<"League", 'String'>
  readonly name: Prisma.FieldRef<"League", 'String'>
  readonly season: Prisma.FieldRef<"League", 'String'>
  readonly sport: Prisma.FieldRef<"League", 'String'>
  readonly teamCount: Prisma.FieldRef<"League", 'Int'>
  readonly createdAt: Prisma.FieldRef<"League", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"League", 'DateTime'>
}
    

// Custom InputTypes
/**
 * League findUnique
 */
export type LeagueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * Filter, which League to fetch.
   */
  where: Prisma.LeagueWhereUniqueInput
}

/**
 * League findUniqueOrThrow
 */
export type LeagueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * Filter, which League to fetch.
   */
  where: Prisma.LeagueWhereUniqueInput
}

/**
 * League findFirst
 */
export type LeagueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * Filter, which League to fetch.
   */
  where?: Prisma.LeagueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leagues to fetch.
   */
  orderBy?: Prisma.LeagueOrderByWithRelationInput | Prisma.LeagueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leagues.
   */
  cursor?: Prisma.LeagueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leagues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leagues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leagues.
   */
  distinct?: Prisma.LeagueScalarFieldEnum | Prisma.LeagueScalarFieldEnum[]
}

/**
 * League findFirstOrThrow
 */
export type LeagueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * Filter, which League to fetch.
   */
  where?: Prisma.LeagueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leagues to fetch.
   */
  orderBy?: Prisma.LeagueOrderByWithRelationInput | Prisma.LeagueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leagues.
   */
  cursor?: Prisma.LeagueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leagues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leagues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leagues.
   */
  distinct?: Prisma.LeagueScalarFieldEnum | Prisma.LeagueScalarFieldEnum[]
}

/**
 * League findMany
 */
export type LeagueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * Filter, which Leagues to fetch.
   */
  where?: Prisma.LeagueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leagues to fetch.
   */
  orderBy?: Prisma.LeagueOrderByWithRelationInput | Prisma.LeagueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Leagues.
   */
  cursor?: Prisma.LeagueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leagues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leagues.
   */
  skip?: number
  distinct?: Prisma.LeagueScalarFieldEnum | Prisma.LeagueScalarFieldEnum[]
}

/**
 * League create
 */
export type LeagueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * The data needed to create a League.
   */
  data: Prisma.XOR<Prisma.LeagueCreateInput, Prisma.LeagueUncheckedCreateInput>
}

/**
 * League createMany
 */
export type LeagueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Leagues.
   */
  data: Prisma.LeagueCreateManyInput | Prisma.LeagueCreateManyInput[]
}

/**
 * League createManyAndReturn
 */
export type LeagueCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * The data used to create many Leagues.
   */
  data: Prisma.LeagueCreateManyInput | Prisma.LeagueCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * League update
 */
export type LeagueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * The data needed to update a League.
   */
  data: Prisma.XOR<Prisma.LeagueUpdateInput, Prisma.LeagueUncheckedUpdateInput>
  /**
   * Choose, which League to update.
   */
  where: Prisma.LeagueWhereUniqueInput
}

/**
 * League updateMany
 */
export type LeagueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Leagues.
   */
  data: Prisma.XOR<Prisma.LeagueUpdateManyMutationInput, Prisma.LeagueUncheckedUpdateManyInput>
  /**
   * Filter which Leagues to update
   */
  where?: Prisma.LeagueWhereInput
  /**
   * Limit how many Leagues to update.
   */
  limit?: number
}

/**
 * League updateManyAndReturn
 */
export type LeagueUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * The data used to update Leagues.
   */
  data: Prisma.XOR<Prisma.LeagueUpdateManyMutationInput, Prisma.LeagueUncheckedUpdateManyInput>
  /**
   * Filter which Leagues to update
   */
  where?: Prisma.LeagueWhereInput
  /**
   * Limit how many Leagues to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * League upsert
 */
export type LeagueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * The filter to search for the League to update in case it exists.
   */
  where: Prisma.LeagueWhereUniqueInput
  /**
   * In case the League found by the `where` argument doesn't exist, create a new League with this data.
   */
  create: Prisma.XOR<Prisma.LeagueCreateInput, Prisma.LeagueUncheckedCreateInput>
  /**
   * In case the League was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeagueUpdateInput, Prisma.LeagueUncheckedUpdateInput>
}

/**
 * League delete
 */
export type LeagueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
  /**
   * Filter which League to delete.
   */
  where: Prisma.LeagueWhereUniqueInput
}

/**
 * League deleteMany
 */
export type LeagueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Leagues to delete
   */
  where?: Prisma.LeagueWhereInput
  /**
   * Limit how many Leagues to delete.
   */
  limit?: number
}

/**
 * League.teams
 */
export type League$teamsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Team
   */
  select?: Prisma.TeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Team
   */
  omit?: Prisma.TeamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamInclude<ExtArgs> | null
  where?: Prisma.TeamWhereInput
  orderBy?: Prisma.TeamOrderByWithRelationInput | Prisma.TeamOrderByWithRelationInput[]
  cursor?: Prisma.TeamWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TeamScalarFieldEnum | Prisma.TeamScalarFieldEnum[]
}

/**
 * League.rosterEntries
 */
export type League$rosterEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  where?: Prisma.RosterEntryWhereInput
  orderBy?: Prisma.RosterEntryOrderByWithRelationInput | Prisma.RosterEntryOrderByWithRelationInput[]
  cursor?: Prisma.RosterEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RosterEntryScalarFieldEnum | Prisma.RosterEntryScalarFieldEnum[]
}

/**
 * League.playerValues
 */
export type League$playerValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  where?: Prisma.PlayerValueWhereInput
  orderBy?: Prisma.PlayerValueOrderByWithRelationInput | Prisma.PlayerValueOrderByWithRelationInput[]
  cursor?: Prisma.PlayerValueWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlayerValueScalarFieldEnum | Prisma.PlayerValueScalarFieldEnum[]
}

/**
 * League.draftPickValues
 */
export type League$draftPickValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DraftPickValue
   */
  select?: Prisma.DraftPickValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DraftPickValue
   */
  omit?: Prisma.DraftPickValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DraftPickValueInclude<ExtArgs> | null
  where?: Prisma.DraftPickValueWhereInput
  orderBy?: Prisma.DraftPickValueOrderByWithRelationInput | Prisma.DraftPickValueOrderByWithRelationInput[]
  cursor?: Prisma.DraftPickValueWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DraftPickValueScalarFieldEnum | Prisma.DraftPickValueScalarFieldEnum[]
}

/**
 * League.teamDraftPicks
 */
export type League$teamDraftPicksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamDraftPick
   */
  select?: Prisma.TeamDraftPickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamDraftPick
   */
  omit?: Prisma.TeamDraftPickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamDraftPickInclude<ExtArgs> | null
  where?: Prisma.TeamDraftPickWhereInput
  orderBy?: Prisma.TeamDraftPickOrderByWithRelationInput | Prisma.TeamDraftPickOrderByWithRelationInput[]
  cursor?: Prisma.TeamDraftPickWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TeamDraftPickScalarFieldEnum | Prisma.TeamDraftPickScalarFieldEnum[]
}

/**
 * League.playerStats
 */
export type League$playerStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerStat
   */
  select?: Prisma.PlayerStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerStat
   */
  omit?: Prisma.PlayerStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerStatInclude<ExtArgs> | null
  where?: Prisma.PlayerStatWhereInput
  orderBy?: Prisma.PlayerStatOrderByWithRelationInput | Prisma.PlayerStatOrderByWithRelationInput[]
  cursor?: Prisma.PlayerStatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlayerStatScalarFieldEnum | Prisma.PlayerStatScalarFieldEnum[]
}

/**
 * League without action
 */
export type LeagueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the League
   */
  select?: Prisma.LeagueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the League
   */
  omit?: Prisma.LeagueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeagueInclude<ExtArgs> | null
}
