
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlayerValue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PlayerValue
 * 
 */
export type PlayerValueModel = runtime.Types.Result.DefaultSelection<Prisma.$PlayerValuePayload>

export type AggregatePlayerValue = {
  _count: PlayerValueCountAggregateOutputType | null
  _avg: PlayerValueAvgAggregateOutputType | null
  _sum: PlayerValueSumAggregateOutputType | null
  _min: PlayerValueMinAggregateOutputType | null
  _max: PlayerValueMaxAggregateOutputType | null
}

export type PlayerValueAvgAggregateOutputType = {
  score: number | null
}

export type PlayerValueSumAggregateOutputType = {
  score: number | null
}

export type PlayerValueMinAggregateOutputType = {
  id: string | null
  playerId: string | null
  leagueId: string | null
  score: number | null
  breakdown: string | null
  updatedAt: Date | null
}

export type PlayerValueMaxAggregateOutputType = {
  id: string | null
  playerId: string | null
  leagueId: string | null
  score: number | null
  breakdown: string | null
  updatedAt: Date | null
}

export type PlayerValueCountAggregateOutputType = {
  id: number
  playerId: number
  leagueId: number
  score: number
  breakdown: number
  updatedAt: number
  _all: number
}


export type PlayerValueAvgAggregateInputType = {
  score?: true
}

export type PlayerValueSumAggregateInputType = {
  score?: true
}

export type PlayerValueMinAggregateInputType = {
  id?: true
  playerId?: true
  leagueId?: true
  score?: true
  breakdown?: true
  updatedAt?: true
}

export type PlayerValueMaxAggregateInputType = {
  id?: true
  playerId?: true
  leagueId?: true
  score?: true
  breakdown?: true
  updatedAt?: true
}

export type PlayerValueCountAggregateInputType = {
  id?: true
  playerId?: true
  leagueId?: true
  score?: true
  breakdown?: true
  updatedAt?: true
  _all?: true
}

export type PlayerValueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlayerValue to aggregate.
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlayerValues to fetch.
   */
  orderBy?: Prisma.PlayerValueOrderByWithRelationInput | Prisma.PlayerValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlayerValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlayerValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlayerValues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlayerValues
  **/
  _count?: true | PlayerValueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlayerValueAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlayerValueSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlayerValueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlayerValueMaxAggregateInputType
}

export type GetPlayerValueAggregateType<T extends PlayerValueAggregateArgs> = {
      [P in keyof T & keyof AggregatePlayerValue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlayerValue[P]>
    : Prisma.GetScalarType<T[P], AggregatePlayerValue[P]>
}




export type PlayerValueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerValueWhereInput
  orderBy?: Prisma.PlayerValueOrderByWithAggregationInput | Prisma.PlayerValueOrderByWithAggregationInput[]
  by: Prisma.PlayerValueScalarFieldEnum[] | Prisma.PlayerValueScalarFieldEnum
  having?: Prisma.PlayerValueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlayerValueCountAggregateInputType | true
  _avg?: PlayerValueAvgAggregateInputType
  _sum?: PlayerValueSumAggregateInputType
  _min?: PlayerValueMinAggregateInputType
  _max?: PlayerValueMaxAggregateInputType
}

export type PlayerValueGroupByOutputType = {
  id: string
  playerId: string
  leagueId: string
  score: number
  breakdown: string | null
  updatedAt: Date
  _count: PlayerValueCountAggregateOutputType | null
  _avg: PlayerValueAvgAggregateOutputType | null
  _sum: PlayerValueSumAggregateOutputType | null
  _min: PlayerValueMinAggregateOutputType | null
  _max: PlayerValueMaxAggregateOutputType | null
}

type GetPlayerValueGroupByPayload<T extends PlayerValueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlayerValueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlayerValueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlayerValueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlayerValueGroupByOutputType[P]>
      }
    >
  >



export type PlayerValueWhereInput = {
  AND?: Prisma.PlayerValueWhereInput | Prisma.PlayerValueWhereInput[]
  OR?: Prisma.PlayerValueWhereInput[]
  NOT?: Prisma.PlayerValueWhereInput | Prisma.PlayerValueWhereInput[]
  id?: Prisma.StringFilter<"PlayerValue"> | string
  playerId?: Prisma.StringFilter<"PlayerValue"> | string
  leagueId?: Prisma.StringFilter<"PlayerValue"> | string
  score?: Prisma.FloatFilter<"PlayerValue"> | number
  breakdown?: Prisma.StringNullableFilter<"PlayerValue"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"PlayerValue"> | Date | string
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
  league?: Prisma.XOR<Prisma.LeagueScalarRelationFilter, Prisma.LeagueWhereInput>
}

export type PlayerValueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  breakdown?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  player?: Prisma.PlayerOrderByWithRelationInput
  league?: Prisma.LeagueOrderByWithRelationInput
}

export type PlayerValueWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  playerId_leagueId?: Prisma.PlayerValuePlayerIdLeagueIdCompoundUniqueInput
  AND?: Prisma.PlayerValueWhereInput | Prisma.PlayerValueWhereInput[]
  OR?: Prisma.PlayerValueWhereInput[]
  NOT?: Prisma.PlayerValueWhereInput | Prisma.PlayerValueWhereInput[]
  playerId?: Prisma.StringFilter<"PlayerValue"> | string
  leagueId?: Prisma.StringFilter<"PlayerValue"> | string
  score?: Prisma.FloatFilter<"PlayerValue"> | number
  breakdown?: Prisma.StringNullableFilter<"PlayerValue"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"PlayerValue"> | Date | string
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
  league?: Prisma.XOR<Prisma.LeagueScalarRelationFilter, Prisma.LeagueWhereInput>
}, "id" | "playerId_leagueId">

export type PlayerValueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  breakdown?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlayerValueCountOrderByAggregateInput
  _avg?: Prisma.PlayerValueAvgOrderByAggregateInput
  _max?: Prisma.PlayerValueMaxOrderByAggregateInput
  _min?: Prisma.PlayerValueMinOrderByAggregateInput
  _sum?: Prisma.PlayerValueSumOrderByAggregateInput
}

export type PlayerValueScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlayerValueScalarWhereWithAggregatesInput | Prisma.PlayerValueScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlayerValueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlayerValueScalarWhereWithAggregatesInput | Prisma.PlayerValueScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlayerValue"> | string
  playerId?: Prisma.StringWithAggregatesFilter<"PlayerValue"> | string
  leagueId?: Prisma.StringWithAggregatesFilter<"PlayerValue"> | string
  score?: Prisma.FloatWithAggregatesFilter<"PlayerValue"> | number
  breakdown?: Prisma.StringNullableWithAggregatesFilter<"PlayerValue"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PlayerValue"> | Date | string
}

export type PlayerValueCreateInput = {
  id?: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
  player: Prisma.PlayerCreateNestedOneWithoutPlayerValuesInput
  league: Prisma.LeagueCreateNestedOneWithoutPlayerValuesInput
}

export type PlayerValueUncheckedCreateInput = {
  id?: string
  playerId: string
  leagueId: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
}

export type PlayerValueUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  player?: Prisma.PlayerUpdateOneRequiredWithoutPlayerValuesNestedInput
  league?: Prisma.LeagueUpdateOneRequiredWithoutPlayerValuesNestedInput
}

export type PlayerValueUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerValueCreateManyInput = {
  id?: string
  playerId: string
  leagueId: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
}

export type PlayerValueUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerValueUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerValueListRelationFilter = {
  every?: Prisma.PlayerValueWhereInput
  some?: Prisma.PlayerValueWhereInput
  none?: Prisma.PlayerValueWhereInput
}

export type PlayerValueOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlayerValuePlayerIdLeagueIdCompoundUniqueInput = {
  playerId: string
  leagueId: string
}

export type PlayerValueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  breakdown?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlayerValueAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type PlayerValueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  breakdown?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlayerValueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  breakdown?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlayerValueSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type PlayerValueCreateNestedManyWithoutLeagueInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutLeagueInput, Prisma.PlayerValueUncheckedCreateWithoutLeagueInput> | Prisma.PlayerValueCreateWithoutLeagueInput[] | Prisma.PlayerValueUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutLeagueInput | Prisma.PlayerValueCreateOrConnectWithoutLeagueInput[]
  createMany?: Prisma.PlayerValueCreateManyLeagueInputEnvelope
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
}

export type PlayerValueUncheckedCreateNestedManyWithoutLeagueInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutLeagueInput, Prisma.PlayerValueUncheckedCreateWithoutLeagueInput> | Prisma.PlayerValueCreateWithoutLeagueInput[] | Prisma.PlayerValueUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutLeagueInput | Prisma.PlayerValueCreateOrConnectWithoutLeagueInput[]
  createMany?: Prisma.PlayerValueCreateManyLeagueInputEnvelope
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
}

export type PlayerValueUpdateManyWithoutLeagueNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutLeagueInput, Prisma.PlayerValueUncheckedCreateWithoutLeagueInput> | Prisma.PlayerValueCreateWithoutLeagueInput[] | Prisma.PlayerValueUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutLeagueInput | Prisma.PlayerValueCreateOrConnectWithoutLeagueInput[]
  upsert?: Prisma.PlayerValueUpsertWithWhereUniqueWithoutLeagueInput | Prisma.PlayerValueUpsertWithWhereUniqueWithoutLeagueInput[]
  createMany?: Prisma.PlayerValueCreateManyLeagueInputEnvelope
  set?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  disconnect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  delete?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  update?: Prisma.PlayerValueUpdateWithWhereUniqueWithoutLeagueInput | Prisma.PlayerValueUpdateWithWhereUniqueWithoutLeagueInput[]
  updateMany?: Prisma.PlayerValueUpdateManyWithWhereWithoutLeagueInput | Prisma.PlayerValueUpdateManyWithWhereWithoutLeagueInput[]
  deleteMany?: Prisma.PlayerValueScalarWhereInput | Prisma.PlayerValueScalarWhereInput[]
}

export type PlayerValueUncheckedUpdateManyWithoutLeagueNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutLeagueInput, Prisma.PlayerValueUncheckedCreateWithoutLeagueInput> | Prisma.PlayerValueCreateWithoutLeagueInput[] | Prisma.PlayerValueUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutLeagueInput | Prisma.PlayerValueCreateOrConnectWithoutLeagueInput[]
  upsert?: Prisma.PlayerValueUpsertWithWhereUniqueWithoutLeagueInput | Prisma.PlayerValueUpsertWithWhereUniqueWithoutLeagueInput[]
  createMany?: Prisma.PlayerValueCreateManyLeagueInputEnvelope
  set?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  disconnect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  delete?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  update?: Prisma.PlayerValueUpdateWithWhereUniqueWithoutLeagueInput | Prisma.PlayerValueUpdateWithWhereUniqueWithoutLeagueInput[]
  updateMany?: Prisma.PlayerValueUpdateManyWithWhereWithoutLeagueInput | Prisma.PlayerValueUpdateManyWithWhereWithoutLeagueInput[]
  deleteMany?: Prisma.PlayerValueScalarWhereInput | Prisma.PlayerValueScalarWhereInput[]
}

export type PlayerValueCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutPlayerInput, Prisma.PlayerValueUncheckedCreateWithoutPlayerInput> | Prisma.PlayerValueCreateWithoutPlayerInput[] | Prisma.PlayerValueUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutPlayerInput | Prisma.PlayerValueCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.PlayerValueCreateManyPlayerInputEnvelope
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
}

export type PlayerValueUncheckedCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutPlayerInput, Prisma.PlayerValueUncheckedCreateWithoutPlayerInput> | Prisma.PlayerValueCreateWithoutPlayerInput[] | Prisma.PlayerValueUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutPlayerInput | Prisma.PlayerValueCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.PlayerValueCreateManyPlayerInputEnvelope
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
}

export type PlayerValueUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutPlayerInput, Prisma.PlayerValueUncheckedCreateWithoutPlayerInput> | Prisma.PlayerValueCreateWithoutPlayerInput[] | Prisma.PlayerValueUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutPlayerInput | Prisma.PlayerValueCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.PlayerValueUpsertWithWhereUniqueWithoutPlayerInput | Prisma.PlayerValueUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.PlayerValueCreateManyPlayerInputEnvelope
  set?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  disconnect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  delete?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  update?: Prisma.PlayerValueUpdateWithWhereUniqueWithoutPlayerInput | Prisma.PlayerValueUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.PlayerValueUpdateManyWithWhereWithoutPlayerInput | Prisma.PlayerValueUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.PlayerValueScalarWhereInput | Prisma.PlayerValueScalarWhereInput[]
}

export type PlayerValueUncheckedUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerValueCreateWithoutPlayerInput, Prisma.PlayerValueUncheckedCreateWithoutPlayerInput> | Prisma.PlayerValueCreateWithoutPlayerInput[] | Prisma.PlayerValueUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.PlayerValueCreateOrConnectWithoutPlayerInput | Prisma.PlayerValueCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.PlayerValueUpsertWithWhereUniqueWithoutPlayerInput | Prisma.PlayerValueUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.PlayerValueCreateManyPlayerInputEnvelope
  set?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  disconnect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  delete?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  connect?: Prisma.PlayerValueWhereUniqueInput | Prisma.PlayerValueWhereUniqueInput[]
  update?: Prisma.PlayerValueUpdateWithWhereUniqueWithoutPlayerInput | Prisma.PlayerValueUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.PlayerValueUpdateManyWithWhereWithoutPlayerInput | Prisma.PlayerValueUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.PlayerValueScalarWhereInput | Prisma.PlayerValueScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PlayerValueCreateWithoutLeagueInput = {
  id?: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
  player: Prisma.PlayerCreateNestedOneWithoutPlayerValuesInput
}

export type PlayerValueUncheckedCreateWithoutLeagueInput = {
  id?: string
  playerId: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
}

export type PlayerValueCreateOrConnectWithoutLeagueInput = {
  where: Prisma.PlayerValueWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerValueCreateWithoutLeagueInput, Prisma.PlayerValueUncheckedCreateWithoutLeagueInput>
}

export type PlayerValueCreateManyLeagueInputEnvelope = {
  data: Prisma.PlayerValueCreateManyLeagueInput | Prisma.PlayerValueCreateManyLeagueInput[]
  skipDuplicates?: boolean
}

export type PlayerValueUpsertWithWhereUniqueWithoutLeagueInput = {
  where: Prisma.PlayerValueWhereUniqueInput
  update: Prisma.XOR<Prisma.PlayerValueUpdateWithoutLeagueInput, Prisma.PlayerValueUncheckedUpdateWithoutLeagueInput>
  create: Prisma.XOR<Prisma.PlayerValueCreateWithoutLeagueInput, Prisma.PlayerValueUncheckedCreateWithoutLeagueInput>
}

export type PlayerValueUpdateWithWhereUniqueWithoutLeagueInput = {
  where: Prisma.PlayerValueWhereUniqueInput
  data: Prisma.XOR<Prisma.PlayerValueUpdateWithoutLeagueInput, Prisma.PlayerValueUncheckedUpdateWithoutLeagueInput>
}

export type PlayerValueUpdateManyWithWhereWithoutLeagueInput = {
  where: Prisma.PlayerValueScalarWhereInput
  data: Prisma.XOR<Prisma.PlayerValueUpdateManyMutationInput, Prisma.PlayerValueUncheckedUpdateManyWithoutLeagueInput>
}

export type PlayerValueScalarWhereInput = {
  AND?: Prisma.PlayerValueScalarWhereInput | Prisma.PlayerValueScalarWhereInput[]
  OR?: Prisma.PlayerValueScalarWhereInput[]
  NOT?: Prisma.PlayerValueScalarWhereInput | Prisma.PlayerValueScalarWhereInput[]
  id?: Prisma.StringFilter<"PlayerValue"> | string
  playerId?: Prisma.StringFilter<"PlayerValue"> | string
  leagueId?: Prisma.StringFilter<"PlayerValue"> | string
  score?: Prisma.FloatFilter<"PlayerValue"> | number
  breakdown?: Prisma.StringNullableFilter<"PlayerValue"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"PlayerValue"> | Date | string
}

export type PlayerValueCreateWithoutPlayerInput = {
  id?: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
  league: Prisma.LeagueCreateNestedOneWithoutPlayerValuesInput
}

export type PlayerValueUncheckedCreateWithoutPlayerInput = {
  id?: string
  leagueId: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
}

export type PlayerValueCreateOrConnectWithoutPlayerInput = {
  where: Prisma.PlayerValueWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerValueCreateWithoutPlayerInput, Prisma.PlayerValueUncheckedCreateWithoutPlayerInput>
}

export type PlayerValueCreateManyPlayerInputEnvelope = {
  data: Prisma.PlayerValueCreateManyPlayerInput | Prisma.PlayerValueCreateManyPlayerInput[]
  skipDuplicates?: boolean
}

export type PlayerValueUpsertWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.PlayerValueWhereUniqueInput
  update: Prisma.XOR<Prisma.PlayerValueUpdateWithoutPlayerInput, Prisma.PlayerValueUncheckedUpdateWithoutPlayerInput>
  create: Prisma.XOR<Prisma.PlayerValueCreateWithoutPlayerInput, Prisma.PlayerValueUncheckedCreateWithoutPlayerInput>
}

export type PlayerValueUpdateWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.PlayerValueWhereUniqueInput
  data: Prisma.XOR<Prisma.PlayerValueUpdateWithoutPlayerInput, Prisma.PlayerValueUncheckedUpdateWithoutPlayerInput>
}

export type PlayerValueUpdateManyWithWhereWithoutPlayerInput = {
  where: Prisma.PlayerValueScalarWhereInput
  data: Prisma.XOR<Prisma.PlayerValueUpdateManyMutationInput, Prisma.PlayerValueUncheckedUpdateManyWithoutPlayerInput>
}

export type PlayerValueCreateManyLeagueInput = {
  id?: string
  playerId: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
}

export type PlayerValueUpdateWithoutLeagueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  player?: Prisma.PlayerUpdateOneRequiredWithoutPlayerValuesNestedInput
}

export type PlayerValueUncheckedUpdateWithoutLeagueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerValueUncheckedUpdateManyWithoutLeagueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerValueCreateManyPlayerInput = {
  id?: string
  leagueId: string
  score: number
  breakdown?: string | null
  updatedAt?: Date | string
}

export type PlayerValueUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  league?: Prisma.LeagueUpdateOneRequiredWithoutPlayerValuesNestedInput
}

export type PlayerValueUncheckedUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerValueUncheckedUpdateManyWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  breakdown?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PlayerValueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerId?: boolean
  leagueId?: boolean
  score?: boolean
  breakdown?: boolean
  updatedAt?: boolean
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playerValue"]>

export type PlayerValueSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerId?: boolean
  leagueId?: boolean
  score?: boolean
  breakdown?: boolean
  updatedAt?: boolean
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playerValue"]>

export type PlayerValueSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerId?: boolean
  leagueId?: boolean
  score?: boolean
  breakdown?: boolean
  updatedAt?: boolean
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playerValue"]>

export type PlayerValueSelectScalar = {
  id?: boolean
  playerId?: boolean
  leagueId?: boolean
  score?: boolean
  breakdown?: boolean
  updatedAt?: boolean
}

export type PlayerValueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "playerId" | "leagueId" | "score" | "breakdown" | "updatedAt", ExtArgs["result"]["playerValue"]>
export type PlayerValueInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
}
export type PlayerValueIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
}
export type PlayerValueIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
}

export type $PlayerValuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlayerValue"
  objects: {
    player: Prisma.$PlayerPayload<ExtArgs>
    league: Prisma.$LeaguePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    playerId: string
    leagueId: string
    score: number
    breakdown: string | null
    updatedAt: Date
  }, ExtArgs["result"]["playerValue"]>
  composites: {}
}

export type PlayerValueGetPayload<S extends boolean | null | undefined | PlayerValueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload, S>

export type PlayerValueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlayerValueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlayerValueCountAggregateInputType | true
  }

export interface PlayerValueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlayerValue'], meta: { name: 'PlayerValue' } }
  /**
   * Find zero or one PlayerValue that matches the filter.
   * @param {PlayerValueFindUniqueArgs} args - Arguments to find a PlayerValue
   * @example
   * // Get one PlayerValue
   * const playerValue = await prisma.playerValue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlayerValueFindUniqueArgs>(args: Prisma.SelectSubset<T, PlayerValueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlayerValue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlayerValueFindUniqueOrThrowArgs} args - Arguments to find a PlayerValue
   * @example
   * // Get one PlayerValue
   * const playerValue = await prisma.playerValue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlayerValueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlayerValueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlayerValue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueFindFirstArgs} args - Arguments to find a PlayerValue
   * @example
   * // Get one PlayerValue
   * const playerValue = await prisma.playerValue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlayerValueFindFirstArgs>(args?: Prisma.SelectSubset<T, PlayerValueFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlayerValue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueFindFirstOrThrowArgs} args - Arguments to find a PlayerValue
   * @example
   * // Get one PlayerValue
   * const playerValue = await prisma.playerValue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlayerValueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlayerValueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlayerValues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlayerValues
   * const playerValues = await prisma.playerValue.findMany()
   * 
   * // Get first 10 PlayerValues
   * const playerValues = await prisma.playerValue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const playerValueWithIdOnly = await prisma.playerValue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlayerValueFindManyArgs>(args?: Prisma.SelectSubset<T, PlayerValueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlayerValue.
   * @param {PlayerValueCreateArgs} args - Arguments to create a PlayerValue.
   * @example
   * // Create one PlayerValue
   * const PlayerValue = await prisma.playerValue.create({
   *   data: {
   *     // ... data to create a PlayerValue
   *   }
   * })
   * 
   */
  create<T extends PlayerValueCreateArgs>(args: Prisma.SelectSubset<T, PlayerValueCreateArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlayerValues.
   * @param {PlayerValueCreateManyArgs} args - Arguments to create many PlayerValues.
   * @example
   * // Create many PlayerValues
   * const playerValue = await prisma.playerValue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlayerValueCreateManyArgs>(args?: Prisma.SelectSubset<T, PlayerValueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlayerValues and returns the data saved in the database.
   * @param {PlayerValueCreateManyAndReturnArgs} args - Arguments to create many PlayerValues.
   * @example
   * // Create many PlayerValues
   * const playerValue = await prisma.playerValue.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlayerValues and only return the `id`
   * const playerValueWithIdOnly = await prisma.playerValue.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlayerValueCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlayerValueCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlayerValue.
   * @param {PlayerValueDeleteArgs} args - Arguments to delete one PlayerValue.
   * @example
   * // Delete one PlayerValue
   * const PlayerValue = await prisma.playerValue.delete({
   *   where: {
   *     // ... filter to delete one PlayerValue
   *   }
   * })
   * 
   */
  delete<T extends PlayerValueDeleteArgs>(args: Prisma.SelectSubset<T, PlayerValueDeleteArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlayerValue.
   * @param {PlayerValueUpdateArgs} args - Arguments to update one PlayerValue.
   * @example
   * // Update one PlayerValue
   * const playerValue = await prisma.playerValue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlayerValueUpdateArgs>(args: Prisma.SelectSubset<T, PlayerValueUpdateArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlayerValues.
   * @param {PlayerValueDeleteManyArgs} args - Arguments to filter PlayerValues to delete.
   * @example
   * // Delete a few PlayerValues
   * const { count } = await prisma.playerValue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlayerValueDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlayerValueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlayerValues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlayerValues
   * const playerValue = await prisma.playerValue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlayerValueUpdateManyArgs>(args: Prisma.SelectSubset<T, PlayerValueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlayerValues and returns the data updated in the database.
   * @param {PlayerValueUpdateManyAndReturnArgs} args - Arguments to update many PlayerValues.
   * @example
   * // Update many PlayerValues
   * const playerValue = await prisma.playerValue.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlayerValues and only return the `id`
   * const playerValueWithIdOnly = await prisma.playerValue.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlayerValueUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlayerValueUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlayerValue.
   * @param {PlayerValueUpsertArgs} args - Arguments to update or create a PlayerValue.
   * @example
   * // Update or create a PlayerValue
   * const playerValue = await prisma.playerValue.upsert({
   *   create: {
   *     // ... data to create a PlayerValue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlayerValue we want to update
   *   }
   * })
   */
  upsert<T extends PlayerValueUpsertArgs>(args: Prisma.SelectSubset<T, PlayerValueUpsertArgs<ExtArgs>>): Prisma.Prisma__PlayerValueClient<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlayerValues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueCountArgs} args - Arguments to filter PlayerValues to count.
   * @example
   * // Count the number of PlayerValues
   * const count = await prisma.playerValue.count({
   *   where: {
   *     // ... the filter for the PlayerValues we want to count
   *   }
   * })
  **/
  count<T extends PlayerValueCountArgs>(
    args?: Prisma.Subset<T, PlayerValueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlayerValueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlayerValue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlayerValueAggregateArgs>(args: Prisma.Subset<T, PlayerValueAggregateArgs>): Prisma.PrismaPromise<GetPlayerValueAggregateType<T>>

  /**
   * Group by PlayerValue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerValueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlayerValueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlayerValueGroupByArgs['orderBy'] }
      : { orderBy?: PlayerValueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlayerValueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlayerValueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlayerValue model
 */
readonly fields: PlayerValueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlayerValue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlayerValueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  player<T extends Prisma.PlayerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlayerDefaultArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  league<T extends Prisma.LeagueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LeagueDefaultArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlayerValue model
 */
export interface PlayerValueFieldRefs {
  readonly id: Prisma.FieldRef<"PlayerValue", 'String'>
  readonly playerId: Prisma.FieldRef<"PlayerValue", 'String'>
  readonly leagueId: Prisma.FieldRef<"PlayerValue", 'String'>
  readonly score: Prisma.FieldRef<"PlayerValue", 'Float'>
  readonly breakdown: Prisma.FieldRef<"PlayerValue", 'String'>
  readonly updatedAt: Prisma.FieldRef<"PlayerValue", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PlayerValue findUnique
 */
export type PlayerValueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * Filter, which PlayerValue to fetch.
   */
  where: Prisma.PlayerValueWhereUniqueInput
}

/**
 * PlayerValue findUniqueOrThrow
 */
export type PlayerValueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * Filter, which PlayerValue to fetch.
   */
  where: Prisma.PlayerValueWhereUniqueInput
}

/**
 * PlayerValue findFirst
 */
export type PlayerValueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * Filter, which PlayerValue to fetch.
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlayerValues to fetch.
   */
  orderBy?: Prisma.PlayerValueOrderByWithRelationInput | Prisma.PlayerValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlayerValues.
   */
  cursor?: Prisma.PlayerValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlayerValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlayerValues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlayerValues.
   */
  distinct?: Prisma.PlayerValueScalarFieldEnum | Prisma.PlayerValueScalarFieldEnum[]
}

/**
 * PlayerValue findFirstOrThrow
 */
export type PlayerValueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * Filter, which PlayerValue to fetch.
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlayerValues to fetch.
   */
  orderBy?: Prisma.PlayerValueOrderByWithRelationInput | Prisma.PlayerValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlayerValues.
   */
  cursor?: Prisma.PlayerValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlayerValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlayerValues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlayerValues.
   */
  distinct?: Prisma.PlayerValueScalarFieldEnum | Prisma.PlayerValueScalarFieldEnum[]
}

/**
 * PlayerValue findMany
 */
export type PlayerValueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * Filter, which PlayerValues to fetch.
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlayerValues to fetch.
   */
  orderBy?: Prisma.PlayerValueOrderByWithRelationInput | Prisma.PlayerValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlayerValues.
   */
  cursor?: Prisma.PlayerValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlayerValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlayerValues.
   */
  skip?: number
  distinct?: Prisma.PlayerValueScalarFieldEnum | Prisma.PlayerValueScalarFieldEnum[]
}

/**
 * PlayerValue create
 */
export type PlayerValueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * The data needed to create a PlayerValue.
   */
  data: Prisma.XOR<Prisma.PlayerValueCreateInput, Prisma.PlayerValueUncheckedCreateInput>
}

/**
 * PlayerValue createMany
 */
export type PlayerValueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlayerValues.
   */
  data: Prisma.PlayerValueCreateManyInput | Prisma.PlayerValueCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlayerValue createManyAndReturn
 */
export type PlayerValueCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * The data used to create many PlayerValues.
   */
  data: Prisma.PlayerValueCreateManyInput | Prisma.PlayerValueCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PlayerValue update
 */
export type PlayerValueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * The data needed to update a PlayerValue.
   */
  data: Prisma.XOR<Prisma.PlayerValueUpdateInput, Prisma.PlayerValueUncheckedUpdateInput>
  /**
   * Choose, which PlayerValue to update.
   */
  where: Prisma.PlayerValueWhereUniqueInput
}

/**
 * PlayerValue updateMany
 */
export type PlayerValueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlayerValues.
   */
  data: Prisma.XOR<Prisma.PlayerValueUpdateManyMutationInput, Prisma.PlayerValueUncheckedUpdateManyInput>
  /**
   * Filter which PlayerValues to update
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * Limit how many PlayerValues to update.
   */
  limit?: number
}

/**
 * PlayerValue updateManyAndReturn
 */
export type PlayerValueUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * The data used to update PlayerValues.
   */
  data: Prisma.XOR<Prisma.PlayerValueUpdateManyMutationInput, Prisma.PlayerValueUncheckedUpdateManyInput>
  /**
   * Filter which PlayerValues to update
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * Limit how many PlayerValues to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PlayerValue upsert
 */
export type PlayerValueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * The filter to search for the PlayerValue to update in case it exists.
   */
  where: Prisma.PlayerValueWhereUniqueInput
  /**
   * In case the PlayerValue found by the `where` argument doesn't exist, create a new PlayerValue with this data.
   */
  create: Prisma.XOR<Prisma.PlayerValueCreateInput, Prisma.PlayerValueUncheckedCreateInput>
  /**
   * In case the PlayerValue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlayerValueUpdateInput, Prisma.PlayerValueUncheckedUpdateInput>
}

/**
 * PlayerValue delete
 */
export type PlayerValueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  /**
   * Filter which PlayerValue to delete.
   */
  where: Prisma.PlayerValueWhereUniqueInput
}

/**
 * PlayerValue deleteMany
 */
export type PlayerValueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlayerValues to delete
   */
  where?: Prisma.PlayerValueWhereInput
  /**
   * Limit how many PlayerValues to delete.
   */
  limit?: number
}

/**
 * PlayerValue without action
 */
export type PlayerValueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
}
