
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Player` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Player
 * 
 */
export type PlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$PlayerPayload>

export type AggregatePlayer = {
  _count: PlayerCountAggregateOutputType | null
  _min: PlayerMinAggregateOutputType | null
  _max: PlayerMaxAggregateOutputType | null
}

export type PlayerMinAggregateOutputType = {
  id: string | null
  playerKey: string | null
  name: string | null
  teamAbbr: string | null
  positions: string | null
  primaryPosition: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlayerMaxAggregateOutputType = {
  id: string | null
  playerKey: string | null
  name: string | null
  teamAbbr: string | null
  positions: string | null
  primaryPosition: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlayerCountAggregateOutputType = {
  id: number
  playerKey: number
  name: number
  teamAbbr: number
  positions: number
  primaryPosition: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PlayerMinAggregateInputType = {
  id?: true
  playerKey?: true
  name?: true
  teamAbbr?: true
  positions?: true
  primaryPosition?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PlayerMaxAggregateInputType = {
  id?: true
  playerKey?: true
  name?: true
  teamAbbr?: true
  positions?: true
  primaryPosition?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type PlayerCountAggregateInputType = {
  id?: true
  playerKey?: true
  name?: true
  teamAbbr?: true
  positions?: true
  primaryPosition?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Player to aggregate.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Players
  **/
  _count?: true | PlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlayerMaxAggregateInputType
}

export type GetPlayerAggregateType<T extends PlayerAggregateArgs> = {
      [P in keyof T & keyof AggregatePlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlayer[P]>
    : Prisma.GetScalarType<T[P], AggregatePlayer[P]>
}




export type PlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerWhereInput
  orderBy?: Prisma.PlayerOrderByWithAggregationInput | Prisma.PlayerOrderByWithAggregationInput[]
  by: Prisma.PlayerScalarFieldEnum[] | Prisma.PlayerScalarFieldEnum
  having?: Prisma.PlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlayerCountAggregateInputType | true
  _min?: PlayerMinAggregateInputType
  _max?: PlayerMaxAggregateInputType
}

export type PlayerGroupByOutputType = {
  id: string
  playerKey: string
  name: string
  teamAbbr: string | null
  positions: string | null
  primaryPosition: string | null
  status: string | null
  createdAt: Date
  updatedAt: Date
  _count: PlayerCountAggregateOutputType | null
  _min: PlayerMinAggregateOutputType | null
  _max: PlayerMaxAggregateOutputType | null
}

type GetPlayerGroupByPayload<T extends PlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlayerGroupByOutputType[P]>
      }
    >
  >



export type PlayerWhereInput = {
  AND?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  OR?: Prisma.PlayerWhereInput[]
  NOT?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  id?: Prisma.StringFilter<"Player"> | string
  playerKey?: Prisma.StringFilter<"Player"> | string
  name?: Prisma.StringFilter<"Player"> | string
  teamAbbr?: Prisma.StringNullableFilter<"Player"> | string | null
  positions?: Prisma.StringNullableFilter<"Player"> | string | null
  primaryPosition?: Prisma.StringNullableFilter<"Player"> | string | null
  status?: Prisma.StringNullableFilter<"Player"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Player"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Player"> | Date | string
  rosterEntries?: Prisma.RosterEntryListRelationFilter
  playerValues?: Prisma.PlayerValueListRelationFilter
  playerStats?: Prisma.PlayerStatListRelationFilter
}

export type PlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  playerKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  teamAbbr?: Prisma.SortOrderInput | Prisma.SortOrder
  positions?: Prisma.SortOrderInput | Prisma.SortOrder
  primaryPosition?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  rosterEntries?: Prisma.RosterEntryOrderByRelationAggregateInput
  playerValues?: Prisma.PlayerValueOrderByRelationAggregateInput
  playerStats?: Prisma.PlayerStatOrderByRelationAggregateInput
}

export type PlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  playerKey?: string
  AND?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  OR?: Prisma.PlayerWhereInput[]
  NOT?: Prisma.PlayerWhereInput | Prisma.PlayerWhereInput[]
  name?: Prisma.StringFilter<"Player"> | string
  teamAbbr?: Prisma.StringNullableFilter<"Player"> | string | null
  positions?: Prisma.StringNullableFilter<"Player"> | string | null
  primaryPosition?: Prisma.StringNullableFilter<"Player"> | string | null
  status?: Prisma.StringNullableFilter<"Player"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Player"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Player"> | Date | string
  rosterEntries?: Prisma.RosterEntryListRelationFilter
  playerValues?: Prisma.PlayerValueListRelationFilter
  playerStats?: Prisma.PlayerStatListRelationFilter
}, "id" | "playerKey">

export type PlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  playerKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  teamAbbr?: Prisma.SortOrderInput | Prisma.SortOrder
  positions?: Prisma.SortOrderInput | Prisma.SortOrder
  primaryPosition?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlayerCountOrderByAggregateInput
  _max?: Prisma.PlayerMaxOrderByAggregateInput
  _min?: Prisma.PlayerMinOrderByAggregateInput
}

export type PlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlayerScalarWhereWithAggregatesInput | Prisma.PlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlayerScalarWhereWithAggregatesInput | Prisma.PlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Player"> | string
  playerKey?: Prisma.StringWithAggregatesFilter<"Player"> | string
  name?: Prisma.StringWithAggregatesFilter<"Player"> | string
  teamAbbr?: Prisma.StringNullableWithAggregatesFilter<"Player"> | string | null
  positions?: Prisma.StringNullableWithAggregatesFilter<"Player"> | string | null
  primaryPosition?: Prisma.StringNullableWithAggregatesFilter<"Player"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"Player"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Player"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Player"> | Date | string
}

export type PlayerCreateInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutPlayerInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutPlayerInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutPlayerInput
}

export type PlayerUncheckedCreateInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutPlayerInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutPlayerInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutPlayerInput
}

export type PlayerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutPlayerNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutPlayerNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutPlayerNestedInput
}

export type PlayerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutPlayerNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutPlayerNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutPlayerNestedInput
}

export type PlayerCreateManyInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlayerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  teamAbbr?: Prisma.SortOrder
  positions?: Prisma.SortOrder
  primaryPosition?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  teamAbbr?: Prisma.SortOrder
  positions?: Prisma.SortOrder
  primaryPosition?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerKey?: Prisma.SortOrder
  name?: Prisma.SortOrder
  teamAbbr?: Prisma.SortOrder
  positions?: Prisma.SortOrder
  primaryPosition?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlayerScalarRelationFilter = {
  is?: Prisma.PlayerWhereInput
  isNot?: Prisma.PlayerWhereInput
}

export type PlayerCreateNestedOneWithoutRosterEntriesInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRosterEntriesInput, Prisma.PlayerUncheckedCreateWithoutRosterEntriesInput>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRosterEntriesInput
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerUpdateOneRequiredWithoutRosterEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutRosterEntriesInput, Prisma.PlayerUncheckedCreateWithoutRosterEntriesInput>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutRosterEntriesInput
  upsert?: Prisma.PlayerUpsertWithoutRosterEntriesInput
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutRosterEntriesInput, Prisma.PlayerUpdateWithoutRosterEntriesInput>, Prisma.PlayerUncheckedUpdateWithoutRosterEntriesInput>
}

export type PlayerCreateNestedOneWithoutPlayerValuesInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerValuesInput, Prisma.PlayerUncheckedCreateWithoutPlayerValuesInput>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutPlayerValuesInput
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerUpdateOneRequiredWithoutPlayerValuesNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerValuesInput, Prisma.PlayerUncheckedCreateWithoutPlayerValuesInput>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutPlayerValuesInput
  upsert?: Prisma.PlayerUpsertWithoutPlayerValuesInput
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutPlayerValuesInput, Prisma.PlayerUpdateWithoutPlayerValuesInput>, Prisma.PlayerUncheckedUpdateWithoutPlayerValuesInput>
}

export type PlayerCreateNestedOneWithoutPlayerStatsInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerStatsInput, Prisma.PlayerUncheckedCreateWithoutPlayerStatsInput>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutPlayerStatsInput
  connect?: Prisma.PlayerWhereUniqueInput
}

export type PlayerUpdateOneRequiredWithoutPlayerStatsNestedInput = {
  create?: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerStatsInput, Prisma.PlayerUncheckedCreateWithoutPlayerStatsInput>
  connectOrCreate?: Prisma.PlayerCreateOrConnectWithoutPlayerStatsInput
  upsert?: Prisma.PlayerUpsertWithoutPlayerStatsInput
  connect?: Prisma.PlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlayerUpdateToOneWithWhereWithoutPlayerStatsInput, Prisma.PlayerUpdateWithoutPlayerStatsInput>, Prisma.PlayerUncheckedUpdateWithoutPlayerStatsInput>
}

export type PlayerCreateWithoutRosterEntriesInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutPlayerInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutPlayerInput
}

export type PlayerUncheckedCreateWithoutRosterEntriesInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutPlayerInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutPlayerInput
}

export type PlayerCreateOrConnectWithoutRosterEntriesInput = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRosterEntriesInput, Prisma.PlayerUncheckedCreateWithoutRosterEntriesInput>
}

export type PlayerUpsertWithoutRosterEntriesInput = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutRosterEntriesInput, Prisma.PlayerUncheckedUpdateWithoutRosterEntriesInput>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutRosterEntriesInput, Prisma.PlayerUncheckedCreateWithoutRosterEntriesInput>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutRosterEntriesInput = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutRosterEntriesInput, Prisma.PlayerUncheckedUpdateWithoutRosterEntriesInput>
}

export type PlayerUpdateWithoutRosterEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  playerValues?: Prisma.PlayerValueUpdateManyWithoutPlayerNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutPlayerNestedInput
}

export type PlayerUncheckedUpdateWithoutRosterEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutPlayerNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutPlayerNestedInput
}

export type PlayerCreateWithoutPlayerValuesInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutPlayerInput
  playerStats?: Prisma.PlayerStatCreateNestedManyWithoutPlayerInput
}

export type PlayerUncheckedCreateWithoutPlayerValuesInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutPlayerInput
  playerStats?: Prisma.PlayerStatUncheckedCreateNestedManyWithoutPlayerInput
}

export type PlayerCreateOrConnectWithoutPlayerValuesInput = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerValuesInput, Prisma.PlayerUncheckedCreateWithoutPlayerValuesInput>
}

export type PlayerUpsertWithoutPlayerValuesInput = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutPlayerValuesInput, Prisma.PlayerUncheckedUpdateWithoutPlayerValuesInput>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerValuesInput, Prisma.PlayerUncheckedCreateWithoutPlayerValuesInput>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutPlayerValuesInput = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutPlayerValuesInput, Prisma.PlayerUncheckedUpdateWithoutPlayerValuesInput>
}

export type PlayerUpdateWithoutPlayerValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutPlayerNestedInput
  playerStats?: Prisma.PlayerStatUpdateManyWithoutPlayerNestedInput
}

export type PlayerUncheckedUpdateWithoutPlayerValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutPlayerNestedInput
  playerStats?: Prisma.PlayerStatUncheckedUpdateManyWithoutPlayerNestedInput
}

export type PlayerCreateWithoutPlayerStatsInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryCreateNestedManyWithoutPlayerInput
  playerValues?: Prisma.PlayerValueCreateNestedManyWithoutPlayerInput
}

export type PlayerUncheckedCreateWithoutPlayerStatsInput = {
  id?: string
  playerKey: string
  name: string
  teamAbbr?: string | null
  positions?: string | null
  primaryPosition?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedCreateNestedManyWithoutPlayerInput
  playerValues?: Prisma.PlayerValueUncheckedCreateNestedManyWithoutPlayerInput
}

export type PlayerCreateOrConnectWithoutPlayerStatsInput = {
  where: Prisma.PlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerStatsInput, Prisma.PlayerUncheckedCreateWithoutPlayerStatsInput>
}

export type PlayerUpsertWithoutPlayerStatsInput = {
  update: Prisma.XOR<Prisma.PlayerUpdateWithoutPlayerStatsInput, Prisma.PlayerUncheckedUpdateWithoutPlayerStatsInput>
  create: Prisma.XOR<Prisma.PlayerCreateWithoutPlayerStatsInput, Prisma.PlayerUncheckedCreateWithoutPlayerStatsInput>
  where?: Prisma.PlayerWhereInput
}

export type PlayerUpdateToOneWithWhereWithoutPlayerStatsInput = {
  where?: Prisma.PlayerWhereInput
  data: Prisma.XOR<Prisma.PlayerUpdateWithoutPlayerStatsInput, Prisma.PlayerUncheckedUpdateWithoutPlayerStatsInput>
}

export type PlayerUpdateWithoutPlayerStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUpdateManyWithoutPlayerNestedInput
  playerValues?: Prisma.PlayerValueUpdateManyWithoutPlayerNestedInput
}

export type PlayerUncheckedUpdateWithoutPlayerStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerKey?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  teamAbbr?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  primaryPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rosterEntries?: Prisma.RosterEntryUncheckedUpdateManyWithoutPlayerNestedInput
  playerValues?: Prisma.PlayerValueUncheckedUpdateManyWithoutPlayerNestedInput
}


/**
 * Count Type PlayerCountOutputType
 */

export type PlayerCountOutputType = {
  rosterEntries: number
  playerValues: number
  playerStats: number
}

export type PlayerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rosterEntries?: boolean | PlayerCountOutputTypeCountRosterEntriesArgs
  playerValues?: boolean | PlayerCountOutputTypeCountPlayerValuesArgs
  playerStats?: boolean | PlayerCountOutputTypeCountPlayerStatsArgs
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerCountOutputType
   */
  select?: Prisma.PlayerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountRosterEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RosterEntryWhereInput
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountPlayerValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerValueWhereInput
}

/**
 * PlayerCountOutputType without action
 */
export type PlayerCountOutputTypeCountPlayerStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayerStatWhereInput
}


export type PlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerKey?: boolean
  name?: boolean
  teamAbbr?: boolean
  positions?: boolean
  primaryPosition?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  rosterEntries?: boolean | Prisma.Player$rosterEntriesArgs<ExtArgs>
  playerValues?: boolean | Prisma.Player$playerValuesArgs<ExtArgs>
  playerStats?: boolean | Prisma.Player$playerStatsArgs<ExtArgs>
  _count?: boolean | Prisma.PlayerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["player"]>

export type PlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerKey?: boolean
  name?: boolean
  teamAbbr?: boolean
  positions?: boolean
  primaryPosition?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["player"]>

export type PlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerKey?: boolean
  name?: boolean
  teamAbbr?: boolean
  positions?: boolean
  primaryPosition?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["player"]>

export type PlayerSelectScalar = {
  id?: boolean
  playerKey?: boolean
  name?: boolean
  teamAbbr?: boolean
  positions?: boolean
  primaryPosition?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "playerKey" | "name" | "teamAbbr" | "positions" | "primaryPosition" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["player"]>
export type PlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rosterEntries?: boolean | Prisma.Player$rosterEntriesArgs<ExtArgs>
  playerValues?: boolean | Prisma.Player$playerValuesArgs<ExtArgs>
  playerStats?: boolean | Prisma.Player$playerStatsArgs<ExtArgs>
  _count?: boolean | Prisma.PlayerCountOutputTypeDefaultArgs<ExtArgs>
}
export type PlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Player"
  objects: {
    rosterEntries: Prisma.$RosterEntryPayload<ExtArgs>[]
    playerValues: Prisma.$PlayerValuePayload<ExtArgs>[]
    playerStats: Prisma.$PlayerStatPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    playerKey: string
    name: string
    teamAbbr: string | null
    positions: string | null
    primaryPosition: string | null
    status: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["player"]>
  composites: {}
}

export type PlayerGetPayload<S extends boolean | null | undefined | PlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlayerPayload, S>

export type PlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlayerCountAggregateInputType | true
  }

export interface PlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Player'], meta: { name: 'Player' } }
  /**
   * Find zero or one Player that matches the filter.
   * @param {PlayerFindUniqueArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, PlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Player that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlayerFindUniqueOrThrowArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Player that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerFindFirstArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, PlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Player that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerFindFirstOrThrowArgs} args - Arguments to find a Player
   * @example
   * // Get one Player
   * const player = await prisma.player.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Players that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Players
   * const players = await prisma.player.findMany()
   * 
   * // Get first 10 Players
   * const players = await prisma.player.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const playerWithIdOnly = await prisma.player.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlayerFindManyArgs>(args?: Prisma.SelectSubset<T, PlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Player.
   * @param {PlayerCreateArgs} args - Arguments to create a Player.
   * @example
   * // Create one Player
   * const Player = await prisma.player.create({
   *   data: {
   *     // ... data to create a Player
   *   }
   * })
   * 
   */
  create<T extends PlayerCreateArgs>(args: Prisma.SelectSubset<T, PlayerCreateArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Players.
   * @param {PlayerCreateManyArgs} args - Arguments to create many Players.
   * @example
   * // Create many Players
   * const player = await prisma.player.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, PlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Players and returns the data saved in the database.
   * @param {PlayerCreateManyAndReturnArgs} args - Arguments to create many Players.
   * @example
   * // Create many Players
   * const player = await prisma.player.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Players and only return the `id`
   * const playerWithIdOnly = await prisma.player.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Player.
   * @param {PlayerDeleteArgs} args - Arguments to delete one Player.
   * @example
   * // Delete one Player
   * const Player = await prisma.player.delete({
   *   where: {
   *     // ... filter to delete one Player
   *   }
   * })
   * 
   */
  delete<T extends PlayerDeleteArgs>(args: Prisma.SelectSubset<T, PlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Player.
   * @param {PlayerUpdateArgs} args - Arguments to update one Player.
   * @example
   * // Update one Player
   * const player = await prisma.player.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlayerUpdateArgs>(args: Prisma.SelectSubset<T, PlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Players.
   * @param {PlayerDeleteManyArgs} args - Arguments to filter Players to delete.
   * @example
   * // Delete a few Players
   * const { count } = await prisma.player.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Players.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Players
   * const player = await prisma.player.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, PlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Players and returns the data updated in the database.
   * @param {PlayerUpdateManyAndReturnArgs} args - Arguments to update many Players.
   * @example
   * // Update many Players
   * const player = await prisma.player.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Players and only return the `id`
   * const playerWithIdOnly = await prisma.player.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Player.
   * @param {PlayerUpsertArgs} args - Arguments to update or create a Player.
   * @example
   * // Update or create a Player
   * const player = await prisma.player.upsert({
   *   create: {
   *     // ... data to create a Player
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Player we want to update
   *   }
   * })
   */
  upsert<T extends PlayerUpsertArgs>(args: Prisma.SelectSubset<T, PlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Players.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerCountArgs} args - Arguments to filter Players to count.
   * @example
   * // Count the number of Players
   * const count = await prisma.player.count({
   *   where: {
   *     // ... the filter for the Players we want to count
   *   }
   * })
  **/
  count<T extends PlayerCountArgs>(
    args?: Prisma.Subset<T, PlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Player.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlayerAggregateArgs>(args: Prisma.Subset<T, PlayerAggregateArgs>): Prisma.PrismaPromise<GetPlayerAggregateType<T>>

  /**
   * Group by Player.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlayerGroupByArgs['orderBy'] }
      : { orderBy?: PlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Player model
 */
readonly fields: PlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Player.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  rosterEntries<T extends Prisma.Player$rosterEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$rosterEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  playerValues<T extends Prisma.Player$playerValuesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$playerValuesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  playerStats<T extends Prisma.Player$playerStatsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Player$playerStatsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayerStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Player model
 */
export interface PlayerFieldRefs {
  readonly id: Prisma.FieldRef<"Player", 'String'>
  readonly playerKey: Prisma.FieldRef<"Player", 'String'>
  readonly name: Prisma.FieldRef<"Player", 'String'>
  readonly teamAbbr: Prisma.FieldRef<"Player", 'String'>
  readonly positions: Prisma.FieldRef<"Player", 'String'>
  readonly primaryPosition: Prisma.FieldRef<"Player", 'String'>
  readonly status: Prisma.FieldRef<"Player", 'String'>
  readonly createdAt: Prisma.FieldRef<"Player", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Player", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Player findUnique
 */
export type PlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player findUniqueOrThrow
 */
export type PlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player findFirst
 */
export type PlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Players.
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Players.
   */
  distinct?: Prisma.PlayerScalarFieldEnum | Prisma.PlayerScalarFieldEnum[]
}

/**
 * Player findFirstOrThrow
 */
export type PlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Player to fetch.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Players.
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Players.
   */
  distinct?: Prisma.PlayerScalarFieldEnum | Prisma.PlayerScalarFieldEnum[]
}

/**
 * Player findMany
 */
export type PlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter, which Players to fetch.
   */
  where?: Prisma.PlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Players to fetch.
   */
  orderBy?: Prisma.PlayerOrderByWithRelationInput | Prisma.PlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Players.
   */
  cursor?: Prisma.PlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Players from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Players.
   */
  skip?: number
  distinct?: Prisma.PlayerScalarFieldEnum | Prisma.PlayerScalarFieldEnum[]
}

/**
 * Player create
 */
export type PlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a Player.
   */
  data: Prisma.XOR<Prisma.PlayerCreateInput, Prisma.PlayerUncheckedCreateInput>
}

/**
 * Player createMany
 */
export type PlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Players.
   */
  data: Prisma.PlayerCreateManyInput | Prisma.PlayerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Player createManyAndReturn
 */
export type PlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * The data used to create many Players.
   */
  data: Prisma.PlayerCreateManyInput | Prisma.PlayerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Player update
 */
export type PlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a Player.
   */
  data: Prisma.XOR<Prisma.PlayerUpdateInput, Prisma.PlayerUncheckedUpdateInput>
  /**
   * Choose, which Player to update.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player updateMany
 */
export type PlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Players.
   */
  data: Prisma.XOR<Prisma.PlayerUpdateManyMutationInput, Prisma.PlayerUncheckedUpdateManyInput>
  /**
   * Filter which Players to update
   */
  where?: Prisma.PlayerWhereInput
  /**
   * Limit how many Players to update.
   */
  limit?: number
}

/**
 * Player updateManyAndReturn
 */
export type PlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * The data used to update Players.
   */
  data: Prisma.XOR<Prisma.PlayerUpdateManyMutationInput, Prisma.PlayerUncheckedUpdateManyInput>
  /**
   * Filter which Players to update
   */
  where?: Prisma.PlayerWhereInput
  /**
   * Limit how many Players to update.
   */
  limit?: number
}

/**
 * Player upsert
 */
export type PlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the Player to update in case it exists.
   */
  where: Prisma.PlayerWhereUniqueInput
  /**
   * In case the Player found by the `where` argument doesn't exist, create a new Player with this data.
   */
  create: Prisma.XOR<Prisma.PlayerCreateInput, Prisma.PlayerUncheckedCreateInput>
  /**
   * In case the Player was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlayerUpdateInput, Prisma.PlayerUncheckedUpdateInput>
}

/**
 * Player delete
 */
export type PlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  /**
   * Filter which Player to delete.
   */
  where: Prisma.PlayerWhereUniqueInput
}

/**
 * Player deleteMany
 */
export type PlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Players to delete
   */
  where?: Prisma.PlayerWhereInput
  /**
   * Limit how many Players to delete.
   */
  limit?: number
}

/**
 * Player.rosterEntries
 */
export type Player$rosterEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  where?: Prisma.RosterEntryWhereInput
  orderBy?: Prisma.RosterEntryOrderByWithRelationInput | Prisma.RosterEntryOrderByWithRelationInput[]
  cursor?: Prisma.RosterEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RosterEntryScalarFieldEnum | Prisma.RosterEntryScalarFieldEnum[]
}

/**
 * Player.playerValues
 */
export type Player$playerValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerValue
   */
  select?: Prisma.PlayerValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerValue
   */
  omit?: Prisma.PlayerValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerValueInclude<ExtArgs> | null
  where?: Prisma.PlayerValueWhereInput
  orderBy?: Prisma.PlayerValueOrderByWithRelationInput | Prisma.PlayerValueOrderByWithRelationInput[]
  cursor?: Prisma.PlayerValueWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlayerValueScalarFieldEnum | Prisma.PlayerValueScalarFieldEnum[]
}

/**
 * Player.playerStats
 */
export type Player$playerStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlayerStat
   */
  select?: Prisma.PlayerStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlayerStat
   */
  omit?: Prisma.PlayerStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerStatInclude<ExtArgs> | null
  where?: Prisma.PlayerStatWhereInput
  orderBy?: Prisma.PlayerStatOrderByWithRelationInput | Prisma.PlayerStatOrderByWithRelationInput[]
  cursor?: Prisma.PlayerStatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlayerStatScalarFieldEnum | Prisma.PlayerStatScalarFieldEnum[]
}

/**
 * Player without action
 */
export type PlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
}
