
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RosterEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RosterEntry
 * 
 */
export type RosterEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$RosterEntryPayload>

export type AggregateRosterEntry = {
  _count: RosterEntryCountAggregateOutputType | null
  _min: RosterEntryMinAggregateOutputType | null
  _max: RosterEntryMaxAggregateOutputType | null
}

export type RosterEntryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  leagueId: string | null
  teamId: string | null
  playerId: string | null
  yahooPosition: string | null
  isBench: boolean | null
  isInjuredList: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RosterEntryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  leagueId: string | null
  teamId: string | null
  playerId: string | null
  yahooPosition: string | null
  isBench: boolean | null
  isInjuredList: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RosterEntryCountAggregateOutputType = {
  id: number
  userId: number
  leagueId: number
  teamId: number
  playerId: number
  yahooPosition: number
  isBench: number
  isInjuredList: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RosterEntryMinAggregateInputType = {
  id?: true
  userId?: true
  leagueId?: true
  teamId?: true
  playerId?: true
  yahooPosition?: true
  isBench?: true
  isInjuredList?: true
  createdAt?: true
  updatedAt?: true
}

export type RosterEntryMaxAggregateInputType = {
  id?: true
  userId?: true
  leagueId?: true
  teamId?: true
  playerId?: true
  yahooPosition?: true
  isBench?: true
  isInjuredList?: true
  createdAt?: true
  updatedAt?: true
}

export type RosterEntryCountAggregateInputType = {
  id?: true
  userId?: true
  leagueId?: true
  teamId?: true
  playerId?: true
  yahooPosition?: true
  isBench?: true
  isInjuredList?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RosterEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RosterEntry to aggregate.
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RosterEntries to fetch.
   */
  orderBy?: Prisma.RosterEntryOrderByWithRelationInput | Prisma.RosterEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RosterEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RosterEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RosterEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RosterEntries
  **/
  _count?: true | RosterEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RosterEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RosterEntryMaxAggregateInputType
}

export type GetRosterEntryAggregateType<T extends RosterEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateRosterEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRosterEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateRosterEntry[P]>
}




export type RosterEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RosterEntryWhereInput
  orderBy?: Prisma.RosterEntryOrderByWithAggregationInput | Prisma.RosterEntryOrderByWithAggregationInput[]
  by: Prisma.RosterEntryScalarFieldEnum[] | Prisma.RosterEntryScalarFieldEnum
  having?: Prisma.RosterEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RosterEntryCountAggregateInputType | true
  _min?: RosterEntryMinAggregateInputType
  _max?: RosterEntryMaxAggregateInputType
}

export type RosterEntryGroupByOutputType = {
  id: string
  userId: string
  leagueId: string
  teamId: string
  playerId: string
  yahooPosition: string | null
  isBench: boolean
  isInjuredList: boolean
  createdAt: Date
  updatedAt: Date
  _count: RosterEntryCountAggregateOutputType | null
  _min: RosterEntryMinAggregateOutputType | null
  _max: RosterEntryMaxAggregateOutputType | null
}

type GetRosterEntryGroupByPayload<T extends RosterEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RosterEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RosterEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RosterEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RosterEntryGroupByOutputType[P]>
      }
    >
  >



export type RosterEntryWhereInput = {
  AND?: Prisma.RosterEntryWhereInput | Prisma.RosterEntryWhereInput[]
  OR?: Prisma.RosterEntryWhereInput[]
  NOT?: Prisma.RosterEntryWhereInput | Prisma.RosterEntryWhereInput[]
  id?: Prisma.StringFilter<"RosterEntry"> | string
  userId?: Prisma.StringFilter<"RosterEntry"> | string
  leagueId?: Prisma.StringFilter<"RosterEntry"> | string
  teamId?: Prisma.StringFilter<"RosterEntry"> | string
  playerId?: Prisma.StringFilter<"RosterEntry"> | string
  yahooPosition?: Prisma.StringNullableFilter<"RosterEntry"> | string | null
  isBench?: Prisma.BoolFilter<"RosterEntry"> | boolean
  isInjuredList?: Prisma.BoolFilter<"RosterEntry"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RosterEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RosterEntry"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  league?: Prisma.XOR<Prisma.LeagueScalarRelationFilter, Prisma.LeagueWhereInput>
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
}

export type RosterEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  yahooPosition?: Prisma.SortOrderInput | Prisma.SortOrder
  isBench?: Prisma.SortOrder
  isInjuredList?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  league?: Prisma.LeagueOrderByWithRelationInput
  team?: Prisma.TeamOrderByWithRelationInput
  player?: Prisma.PlayerOrderByWithRelationInput
}

export type RosterEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RosterEntryWhereInput | Prisma.RosterEntryWhereInput[]
  OR?: Prisma.RosterEntryWhereInput[]
  NOT?: Prisma.RosterEntryWhereInput | Prisma.RosterEntryWhereInput[]
  userId?: Prisma.StringFilter<"RosterEntry"> | string
  leagueId?: Prisma.StringFilter<"RosterEntry"> | string
  teamId?: Prisma.StringFilter<"RosterEntry"> | string
  playerId?: Prisma.StringFilter<"RosterEntry"> | string
  yahooPosition?: Prisma.StringNullableFilter<"RosterEntry"> | string | null
  isBench?: Prisma.BoolFilter<"RosterEntry"> | boolean
  isInjuredList?: Prisma.BoolFilter<"RosterEntry"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RosterEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RosterEntry"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  league?: Prisma.XOR<Prisma.LeagueScalarRelationFilter, Prisma.LeagueWhereInput>
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
}, "id">

export type RosterEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  yahooPosition?: Prisma.SortOrderInput | Prisma.SortOrder
  isBench?: Prisma.SortOrder
  isInjuredList?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RosterEntryCountOrderByAggregateInput
  _max?: Prisma.RosterEntryMaxOrderByAggregateInput
  _min?: Prisma.RosterEntryMinOrderByAggregateInput
}

export type RosterEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.RosterEntryScalarWhereWithAggregatesInput | Prisma.RosterEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.RosterEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RosterEntryScalarWhereWithAggregatesInput | Prisma.RosterEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RosterEntry"> | string
  userId?: Prisma.StringWithAggregatesFilter<"RosterEntry"> | string
  leagueId?: Prisma.StringWithAggregatesFilter<"RosterEntry"> | string
  teamId?: Prisma.StringWithAggregatesFilter<"RosterEntry"> | string
  playerId?: Prisma.StringWithAggregatesFilter<"RosterEntry"> | string
  yahooPosition?: Prisma.StringNullableWithAggregatesFilter<"RosterEntry"> | string | null
  isBench?: Prisma.BoolWithAggregatesFilter<"RosterEntry"> | boolean
  isInjuredList?: Prisma.BoolWithAggregatesFilter<"RosterEntry"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RosterEntry"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RosterEntry"> | Date | string
}

export type RosterEntryCreateInput = {
  id?: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRosterEntriesInput
  league: Prisma.LeagueCreateNestedOneWithoutRosterEntriesInput
  team: Prisma.TeamCreateNestedOneWithoutRosterEntriesInput
  player: Prisma.PlayerCreateNestedOneWithoutRosterEntriesInput
}

export type RosterEntryUncheckedCreateInput = {
  id?: string
  userId: string
  leagueId: string
  teamId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRosterEntriesNestedInput
  league?: Prisma.LeagueUpdateOneRequiredWithoutRosterEntriesNestedInput
  team?: Prisma.TeamUpdateOneRequiredWithoutRosterEntriesNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutRosterEntriesNestedInput
}

export type RosterEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryCreateManyInput = {
  id?: string
  userId: string
  leagueId: string
  teamId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryListRelationFilter = {
  every?: Prisma.RosterEntryWhereInput
  some?: Prisma.RosterEntryWhereInput
  none?: Prisma.RosterEntryWhereInput
}

export type RosterEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RosterEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  yahooPosition?: Prisma.SortOrder
  isBench?: Prisma.SortOrder
  isInjuredList?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RosterEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  yahooPosition?: Prisma.SortOrder
  isBench?: Prisma.SortOrder
  isInjuredList?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RosterEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  leagueId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  yahooPosition?: Prisma.SortOrder
  isBench?: Prisma.SortOrder
  isInjuredList?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RosterEntryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutUserInput, Prisma.RosterEntryUncheckedCreateWithoutUserInput> | Prisma.RosterEntryCreateWithoutUserInput[] | Prisma.RosterEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutUserInput | Prisma.RosterEntryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RosterEntryCreateManyUserInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutUserInput, Prisma.RosterEntryUncheckedCreateWithoutUserInput> | Prisma.RosterEntryCreateWithoutUserInput[] | Prisma.RosterEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutUserInput | Prisma.RosterEntryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RosterEntryCreateManyUserInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutUserInput, Prisma.RosterEntryUncheckedCreateWithoutUserInput> | Prisma.RosterEntryCreateWithoutUserInput[] | Prisma.RosterEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutUserInput | Prisma.RosterEntryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutUserInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RosterEntryCreateManyUserInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutUserInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutUserInput | Prisma.RosterEntryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutUserInput, Prisma.RosterEntryUncheckedCreateWithoutUserInput> | Prisma.RosterEntryCreateWithoutUserInput[] | Prisma.RosterEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutUserInput | Prisma.RosterEntryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutUserInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RosterEntryCreateManyUserInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutUserInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutUserInput | Prisma.RosterEntryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryCreateNestedManyWithoutLeagueInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutLeagueInput, Prisma.RosterEntryUncheckedCreateWithoutLeagueInput> | Prisma.RosterEntryCreateWithoutLeagueInput[] | Prisma.RosterEntryUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutLeagueInput | Prisma.RosterEntryCreateOrConnectWithoutLeagueInput[]
  createMany?: Prisma.RosterEntryCreateManyLeagueInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUncheckedCreateNestedManyWithoutLeagueInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutLeagueInput, Prisma.RosterEntryUncheckedCreateWithoutLeagueInput> | Prisma.RosterEntryCreateWithoutLeagueInput[] | Prisma.RosterEntryUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutLeagueInput | Prisma.RosterEntryCreateOrConnectWithoutLeagueInput[]
  createMany?: Prisma.RosterEntryCreateManyLeagueInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUpdateManyWithoutLeagueNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutLeagueInput, Prisma.RosterEntryUncheckedCreateWithoutLeagueInput> | Prisma.RosterEntryCreateWithoutLeagueInput[] | Prisma.RosterEntryUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutLeagueInput | Prisma.RosterEntryCreateOrConnectWithoutLeagueInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutLeagueInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutLeagueInput[]
  createMany?: Prisma.RosterEntryCreateManyLeagueInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutLeagueInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutLeagueInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutLeagueInput | Prisma.RosterEntryUpdateManyWithWhereWithoutLeagueInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryUncheckedUpdateManyWithoutLeagueNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutLeagueInput, Prisma.RosterEntryUncheckedCreateWithoutLeagueInput> | Prisma.RosterEntryCreateWithoutLeagueInput[] | Prisma.RosterEntryUncheckedCreateWithoutLeagueInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutLeagueInput | Prisma.RosterEntryCreateOrConnectWithoutLeagueInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutLeagueInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutLeagueInput[]
  createMany?: Prisma.RosterEntryCreateManyLeagueInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutLeagueInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutLeagueInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutLeagueInput | Prisma.RosterEntryUpdateManyWithWhereWithoutLeagueInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutTeamInput, Prisma.RosterEntryUncheckedCreateWithoutTeamInput> | Prisma.RosterEntryCreateWithoutTeamInput[] | Prisma.RosterEntryUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutTeamInput | Prisma.RosterEntryCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.RosterEntryCreateManyTeamInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutTeamInput, Prisma.RosterEntryUncheckedCreateWithoutTeamInput> | Prisma.RosterEntryCreateWithoutTeamInput[] | Prisma.RosterEntryUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutTeamInput | Prisma.RosterEntryCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.RosterEntryCreateManyTeamInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutTeamInput, Prisma.RosterEntryUncheckedCreateWithoutTeamInput> | Prisma.RosterEntryCreateWithoutTeamInput[] | Prisma.RosterEntryUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutTeamInput | Prisma.RosterEntryCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutTeamInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.RosterEntryCreateManyTeamInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutTeamInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutTeamInput | Prisma.RosterEntryUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutTeamInput, Prisma.RosterEntryUncheckedCreateWithoutTeamInput> | Prisma.RosterEntryCreateWithoutTeamInput[] | Prisma.RosterEntryUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutTeamInput | Prisma.RosterEntryCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutTeamInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.RosterEntryCreateManyTeamInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutTeamInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutTeamInput | Prisma.RosterEntryUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutPlayerInput, Prisma.RosterEntryUncheckedCreateWithoutPlayerInput> | Prisma.RosterEntryCreateWithoutPlayerInput[] | Prisma.RosterEntryUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutPlayerInput | Prisma.RosterEntryCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.RosterEntryCreateManyPlayerInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUncheckedCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutPlayerInput, Prisma.RosterEntryUncheckedCreateWithoutPlayerInput> | Prisma.RosterEntryCreateWithoutPlayerInput[] | Prisma.RosterEntryUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutPlayerInput | Prisma.RosterEntryCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.RosterEntryCreateManyPlayerInputEnvelope
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
}

export type RosterEntryUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutPlayerInput, Prisma.RosterEntryUncheckedCreateWithoutPlayerInput> | Prisma.RosterEntryCreateWithoutPlayerInput[] | Prisma.RosterEntryUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutPlayerInput | Prisma.RosterEntryCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutPlayerInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.RosterEntryCreateManyPlayerInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutPlayerInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutPlayerInput | Prisma.RosterEntryUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type RosterEntryUncheckedUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.RosterEntryCreateWithoutPlayerInput, Prisma.RosterEntryUncheckedCreateWithoutPlayerInput> | Prisma.RosterEntryCreateWithoutPlayerInput[] | Prisma.RosterEntryUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.RosterEntryCreateOrConnectWithoutPlayerInput | Prisma.RosterEntryCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.RosterEntryUpsertWithWhereUniqueWithoutPlayerInput | Prisma.RosterEntryUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.RosterEntryCreateManyPlayerInputEnvelope
  set?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  disconnect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  delete?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  connect?: Prisma.RosterEntryWhereUniqueInput | Prisma.RosterEntryWhereUniqueInput[]
  update?: Prisma.RosterEntryUpdateWithWhereUniqueWithoutPlayerInput | Prisma.RosterEntryUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.RosterEntryUpdateManyWithWhereWithoutPlayerInput | Prisma.RosterEntryUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type RosterEntryCreateWithoutUserInput = {
  id?: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  league: Prisma.LeagueCreateNestedOneWithoutRosterEntriesInput
  team: Prisma.TeamCreateNestedOneWithoutRosterEntriesInput
  player: Prisma.PlayerCreateNestedOneWithoutRosterEntriesInput
}

export type RosterEntryUncheckedCreateWithoutUserInput = {
  id?: string
  leagueId: string
  teamId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryCreateOrConnectWithoutUserInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutUserInput, Prisma.RosterEntryUncheckedCreateWithoutUserInput>
}

export type RosterEntryCreateManyUserInputEnvelope = {
  data: Prisma.RosterEntryCreateManyUserInput | Prisma.RosterEntryCreateManyUserInput[]
}

export type RosterEntryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.RosterEntryUpdateWithoutUserInput, Prisma.RosterEntryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutUserInput, Prisma.RosterEntryUncheckedCreateWithoutUserInput>
}

export type RosterEntryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateWithoutUserInput, Prisma.RosterEntryUncheckedUpdateWithoutUserInput>
}

export type RosterEntryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.RosterEntryScalarWhereInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateManyMutationInput, Prisma.RosterEntryUncheckedUpdateManyWithoutUserInput>
}

export type RosterEntryScalarWhereInput = {
  AND?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
  OR?: Prisma.RosterEntryScalarWhereInput[]
  NOT?: Prisma.RosterEntryScalarWhereInput | Prisma.RosterEntryScalarWhereInput[]
  id?: Prisma.StringFilter<"RosterEntry"> | string
  userId?: Prisma.StringFilter<"RosterEntry"> | string
  leagueId?: Prisma.StringFilter<"RosterEntry"> | string
  teamId?: Prisma.StringFilter<"RosterEntry"> | string
  playerId?: Prisma.StringFilter<"RosterEntry"> | string
  yahooPosition?: Prisma.StringNullableFilter<"RosterEntry"> | string | null
  isBench?: Prisma.BoolFilter<"RosterEntry"> | boolean
  isInjuredList?: Prisma.BoolFilter<"RosterEntry"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RosterEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RosterEntry"> | Date | string
}

export type RosterEntryCreateWithoutLeagueInput = {
  id?: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRosterEntriesInput
  team: Prisma.TeamCreateNestedOneWithoutRosterEntriesInput
  player: Prisma.PlayerCreateNestedOneWithoutRosterEntriesInput
}

export type RosterEntryUncheckedCreateWithoutLeagueInput = {
  id?: string
  userId: string
  teamId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryCreateOrConnectWithoutLeagueInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutLeagueInput, Prisma.RosterEntryUncheckedCreateWithoutLeagueInput>
}

export type RosterEntryCreateManyLeagueInputEnvelope = {
  data: Prisma.RosterEntryCreateManyLeagueInput | Prisma.RosterEntryCreateManyLeagueInput[]
}

export type RosterEntryUpsertWithWhereUniqueWithoutLeagueInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.RosterEntryUpdateWithoutLeagueInput, Prisma.RosterEntryUncheckedUpdateWithoutLeagueInput>
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutLeagueInput, Prisma.RosterEntryUncheckedCreateWithoutLeagueInput>
}

export type RosterEntryUpdateWithWhereUniqueWithoutLeagueInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateWithoutLeagueInput, Prisma.RosterEntryUncheckedUpdateWithoutLeagueInput>
}

export type RosterEntryUpdateManyWithWhereWithoutLeagueInput = {
  where: Prisma.RosterEntryScalarWhereInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateManyMutationInput, Prisma.RosterEntryUncheckedUpdateManyWithoutLeagueInput>
}

export type RosterEntryCreateWithoutTeamInput = {
  id?: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRosterEntriesInput
  league: Prisma.LeagueCreateNestedOneWithoutRosterEntriesInput
  player: Prisma.PlayerCreateNestedOneWithoutRosterEntriesInput
}

export type RosterEntryUncheckedCreateWithoutTeamInput = {
  id?: string
  userId: string
  leagueId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryCreateOrConnectWithoutTeamInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutTeamInput, Prisma.RosterEntryUncheckedCreateWithoutTeamInput>
}

export type RosterEntryCreateManyTeamInputEnvelope = {
  data: Prisma.RosterEntryCreateManyTeamInput | Prisma.RosterEntryCreateManyTeamInput[]
}

export type RosterEntryUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.RosterEntryUpdateWithoutTeamInput, Prisma.RosterEntryUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutTeamInput, Prisma.RosterEntryUncheckedCreateWithoutTeamInput>
}

export type RosterEntryUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateWithoutTeamInput, Prisma.RosterEntryUncheckedUpdateWithoutTeamInput>
}

export type RosterEntryUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.RosterEntryScalarWhereInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateManyMutationInput, Prisma.RosterEntryUncheckedUpdateManyWithoutTeamInput>
}

export type RosterEntryCreateWithoutPlayerInput = {
  id?: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRosterEntriesInput
  league: Prisma.LeagueCreateNestedOneWithoutRosterEntriesInput
  team: Prisma.TeamCreateNestedOneWithoutRosterEntriesInput
}

export type RosterEntryUncheckedCreateWithoutPlayerInput = {
  id?: string
  userId: string
  leagueId: string
  teamId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryCreateOrConnectWithoutPlayerInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutPlayerInput, Prisma.RosterEntryUncheckedCreateWithoutPlayerInput>
}

export type RosterEntryCreateManyPlayerInputEnvelope = {
  data: Prisma.RosterEntryCreateManyPlayerInput | Prisma.RosterEntryCreateManyPlayerInput[]
}

export type RosterEntryUpsertWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.RosterEntryUpdateWithoutPlayerInput, Prisma.RosterEntryUncheckedUpdateWithoutPlayerInput>
  create: Prisma.XOR<Prisma.RosterEntryCreateWithoutPlayerInput, Prisma.RosterEntryUncheckedCreateWithoutPlayerInput>
}

export type RosterEntryUpdateWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.RosterEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateWithoutPlayerInput, Prisma.RosterEntryUncheckedUpdateWithoutPlayerInput>
}

export type RosterEntryUpdateManyWithWhereWithoutPlayerInput = {
  where: Prisma.RosterEntryScalarWhereInput
  data: Prisma.XOR<Prisma.RosterEntryUpdateManyMutationInput, Prisma.RosterEntryUncheckedUpdateManyWithoutPlayerInput>
}

export type RosterEntryCreateManyUserInput = {
  id?: string
  leagueId: string
  teamId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  league?: Prisma.LeagueUpdateOneRequiredWithoutRosterEntriesNestedInput
  team?: Prisma.TeamUpdateOneRequiredWithoutRosterEntriesNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutRosterEntriesNestedInput
}

export type RosterEntryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryCreateManyLeagueInput = {
  id?: string
  userId: string
  teamId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryUpdateWithoutLeagueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRosterEntriesNestedInput
  team?: Prisma.TeamUpdateOneRequiredWithoutRosterEntriesNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutRosterEntriesNestedInput
}

export type RosterEntryUncheckedUpdateWithoutLeagueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryUncheckedUpdateManyWithoutLeagueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryCreateManyTeamInput = {
  id?: string
  userId: string
  leagueId: string
  playerId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRosterEntriesNestedInput
  league?: Prisma.LeagueUpdateOneRequiredWithoutRosterEntriesNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutRosterEntriesNestedInput
}

export type RosterEntryUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryCreateManyPlayerInput = {
  id?: string
  userId: string
  leagueId: string
  teamId: string
  yahooPosition?: string | null
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RosterEntryUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRosterEntriesNestedInput
  league?: Prisma.LeagueUpdateOneRequiredWithoutRosterEntriesNestedInput
  team?: Prisma.TeamUpdateOneRequiredWithoutRosterEntriesNestedInput
}

export type RosterEntryUncheckedUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RosterEntryUncheckedUpdateManyWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  leagueId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  yahooPosition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBench?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInjuredList?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RosterEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  leagueId?: boolean
  teamId?: boolean
  playerId?: boolean
  yahooPosition?: boolean
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rosterEntry"]>

export type RosterEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  leagueId?: boolean
  teamId?: boolean
  playerId?: boolean
  yahooPosition?: boolean
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rosterEntry"]>

export type RosterEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  leagueId?: boolean
  teamId?: boolean
  playerId?: boolean
  yahooPosition?: boolean
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rosterEntry"]>

export type RosterEntrySelectScalar = {
  id?: boolean
  userId?: boolean
  leagueId?: boolean
  teamId?: boolean
  playerId?: boolean
  yahooPosition?: boolean
  isBench?: boolean
  isInjuredList?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RosterEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "leagueId" | "teamId" | "playerId" | "yahooPosition" | "isBench" | "isInjuredList" | "createdAt" | "updatedAt", ExtArgs["result"]["rosterEntry"]>
export type RosterEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}
export type RosterEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}
export type RosterEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  league?: boolean | Prisma.LeagueDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}

export type $RosterEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RosterEntry"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    league: Prisma.$LeaguePayload<ExtArgs>
    team: Prisma.$TeamPayload<ExtArgs>
    player: Prisma.$PlayerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    leagueId: string
    teamId: string
    playerId: string
    yahooPosition: string | null
    isBench: boolean
    isInjuredList: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["rosterEntry"]>
  composites: {}
}

export type RosterEntryGetPayload<S extends boolean | null | undefined | RosterEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload, S>

export type RosterEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RosterEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RosterEntryCountAggregateInputType | true
  }

export interface RosterEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RosterEntry'], meta: { name: 'RosterEntry' } }
  /**
   * Find zero or one RosterEntry that matches the filter.
   * @param {RosterEntryFindUniqueArgs} args - Arguments to find a RosterEntry
   * @example
   * // Get one RosterEntry
   * const rosterEntry = await prisma.rosterEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RosterEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, RosterEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RosterEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RosterEntryFindUniqueOrThrowArgs} args - Arguments to find a RosterEntry
   * @example
   * // Get one RosterEntry
   * const rosterEntry = await prisma.rosterEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RosterEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RosterEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RosterEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryFindFirstArgs} args - Arguments to find a RosterEntry
   * @example
   * // Get one RosterEntry
   * const rosterEntry = await prisma.rosterEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RosterEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, RosterEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RosterEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryFindFirstOrThrowArgs} args - Arguments to find a RosterEntry
   * @example
   * // Get one RosterEntry
   * const rosterEntry = await prisma.rosterEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RosterEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RosterEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RosterEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RosterEntries
   * const rosterEntries = await prisma.rosterEntry.findMany()
   * 
   * // Get first 10 RosterEntries
   * const rosterEntries = await prisma.rosterEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rosterEntryWithIdOnly = await prisma.rosterEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RosterEntryFindManyArgs>(args?: Prisma.SelectSubset<T, RosterEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RosterEntry.
   * @param {RosterEntryCreateArgs} args - Arguments to create a RosterEntry.
   * @example
   * // Create one RosterEntry
   * const RosterEntry = await prisma.rosterEntry.create({
   *   data: {
   *     // ... data to create a RosterEntry
   *   }
   * })
   * 
   */
  create<T extends RosterEntryCreateArgs>(args: Prisma.SelectSubset<T, RosterEntryCreateArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RosterEntries.
   * @param {RosterEntryCreateManyArgs} args - Arguments to create many RosterEntries.
   * @example
   * // Create many RosterEntries
   * const rosterEntry = await prisma.rosterEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RosterEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, RosterEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RosterEntries and returns the data saved in the database.
   * @param {RosterEntryCreateManyAndReturnArgs} args - Arguments to create many RosterEntries.
   * @example
   * // Create many RosterEntries
   * const rosterEntry = await prisma.rosterEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RosterEntries and only return the `id`
   * const rosterEntryWithIdOnly = await prisma.rosterEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RosterEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RosterEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RosterEntry.
   * @param {RosterEntryDeleteArgs} args - Arguments to delete one RosterEntry.
   * @example
   * // Delete one RosterEntry
   * const RosterEntry = await prisma.rosterEntry.delete({
   *   where: {
   *     // ... filter to delete one RosterEntry
   *   }
   * })
   * 
   */
  delete<T extends RosterEntryDeleteArgs>(args: Prisma.SelectSubset<T, RosterEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RosterEntry.
   * @param {RosterEntryUpdateArgs} args - Arguments to update one RosterEntry.
   * @example
   * // Update one RosterEntry
   * const rosterEntry = await prisma.rosterEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RosterEntryUpdateArgs>(args: Prisma.SelectSubset<T, RosterEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RosterEntries.
   * @param {RosterEntryDeleteManyArgs} args - Arguments to filter RosterEntries to delete.
   * @example
   * // Delete a few RosterEntries
   * const { count } = await prisma.rosterEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RosterEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, RosterEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RosterEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RosterEntries
   * const rosterEntry = await prisma.rosterEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RosterEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, RosterEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RosterEntries and returns the data updated in the database.
   * @param {RosterEntryUpdateManyAndReturnArgs} args - Arguments to update many RosterEntries.
   * @example
   * // Update many RosterEntries
   * const rosterEntry = await prisma.rosterEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RosterEntries and only return the `id`
   * const rosterEntryWithIdOnly = await prisma.rosterEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RosterEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RosterEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RosterEntry.
   * @param {RosterEntryUpsertArgs} args - Arguments to update or create a RosterEntry.
   * @example
   * // Update or create a RosterEntry
   * const rosterEntry = await prisma.rosterEntry.upsert({
   *   create: {
   *     // ... data to create a RosterEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RosterEntry we want to update
   *   }
   * })
   */
  upsert<T extends RosterEntryUpsertArgs>(args: Prisma.SelectSubset<T, RosterEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__RosterEntryClient<runtime.Types.Result.GetResult<Prisma.$RosterEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RosterEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryCountArgs} args - Arguments to filter RosterEntries to count.
   * @example
   * // Count the number of RosterEntries
   * const count = await prisma.rosterEntry.count({
   *   where: {
   *     // ... the filter for the RosterEntries we want to count
   *   }
   * })
  **/
  count<T extends RosterEntryCountArgs>(
    args?: Prisma.Subset<T, RosterEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RosterEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RosterEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RosterEntryAggregateArgs>(args: Prisma.Subset<T, RosterEntryAggregateArgs>): Prisma.PrismaPromise<GetRosterEntryAggregateType<T>>

  /**
   * Group by RosterEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RosterEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RosterEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RosterEntryGroupByArgs['orderBy'] }
      : { orderBy?: RosterEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RosterEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRosterEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RosterEntry model
 */
readonly fields: RosterEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RosterEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RosterEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  league<T extends Prisma.LeagueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LeagueDefaultArgs<ExtArgs>>): Prisma.Prisma__LeagueClient<runtime.Types.Result.GetResult<Prisma.$LeaguePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  player<T extends Prisma.PlayerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlayerDefaultArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RosterEntry model
 */
export interface RosterEntryFieldRefs {
  readonly id: Prisma.FieldRef<"RosterEntry", 'String'>
  readonly userId: Prisma.FieldRef<"RosterEntry", 'String'>
  readonly leagueId: Prisma.FieldRef<"RosterEntry", 'String'>
  readonly teamId: Prisma.FieldRef<"RosterEntry", 'String'>
  readonly playerId: Prisma.FieldRef<"RosterEntry", 'String'>
  readonly yahooPosition: Prisma.FieldRef<"RosterEntry", 'String'>
  readonly isBench: Prisma.FieldRef<"RosterEntry", 'Boolean'>
  readonly isInjuredList: Prisma.FieldRef<"RosterEntry", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"RosterEntry", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RosterEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RosterEntry findUnique
 */
export type RosterEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * Filter, which RosterEntry to fetch.
   */
  where: Prisma.RosterEntryWhereUniqueInput
}

/**
 * RosterEntry findUniqueOrThrow
 */
export type RosterEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * Filter, which RosterEntry to fetch.
   */
  where: Prisma.RosterEntryWhereUniqueInput
}

/**
 * RosterEntry findFirst
 */
export type RosterEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * Filter, which RosterEntry to fetch.
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RosterEntries to fetch.
   */
  orderBy?: Prisma.RosterEntryOrderByWithRelationInput | Prisma.RosterEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RosterEntries.
   */
  cursor?: Prisma.RosterEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RosterEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RosterEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RosterEntries.
   */
  distinct?: Prisma.RosterEntryScalarFieldEnum | Prisma.RosterEntryScalarFieldEnum[]
}

/**
 * RosterEntry findFirstOrThrow
 */
export type RosterEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * Filter, which RosterEntry to fetch.
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RosterEntries to fetch.
   */
  orderBy?: Prisma.RosterEntryOrderByWithRelationInput | Prisma.RosterEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RosterEntries.
   */
  cursor?: Prisma.RosterEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RosterEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RosterEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RosterEntries.
   */
  distinct?: Prisma.RosterEntryScalarFieldEnum | Prisma.RosterEntryScalarFieldEnum[]
}

/**
 * RosterEntry findMany
 */
export type RosterEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * Filter, which RosterEntries to fetch.
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RosterEntries to fetch.
   */
  orderBy?: Prisma.RosterEntryOrderByWithRelationInput | Prisma.RosterEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RosterEntries.
   */
  cursor?: Prisma.RosterEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RosterEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RosterEntries.
   */
  skip?: number
  distinct?: Prisma.RosterEntryScalarFieldEnum | Prisma.RosterEntryScalarFieldEnum[]
}

/**
 * RosterEntry create
 */
export type RosterEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a RosterEntry.
   */
  data: Prisma.XOR<Prisma.RosterEntryCreateInput, Prisma.RosterEntryUncheckedCreateInput>
}

/**
 * RosterEntry createMany
 */
export type RosterEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RosterEntries.
   */
  data: Prisma.RosterEntryCreateManyInput | Prisma.RosterEntryCreateManyInput[]
}

/**
 * RosterEntry createManyAndReturn
 */
export type RosterEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * The data used to create many RosterEntries.
   */
  data: Prisma.RosterEntryCreateManyInput | Prisma.RosterEntryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RosterEntry update
 */
export type RosterEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a RosterEntry.
   */
  data: Prisma.XOR<Prisma.RosterEntryUpdateInput, Prisma.RosterEntryUncheckedUpdateInput>
  /**
   * Choose, which RosterEntry to update.
   */
  where: Prisma.RosterEntryWhereUniqueInput
}

/**
 * RosterEntry updateMany
 */
export type RosterEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RosterEntries.
   */
  data: Prisma.XOR<Prisma.RosterEntryUpdateManyMutationInput, Prisma.RosterEntryUncheckedUpdateManyInput>
  /**
   * Filter which RosterEntries to update
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * Limit how many RosterEntries to update.
   */
  limit?: number
}

/**
 * RosterEntry updateManyAndReturn
 */
export type RosterEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * The data used to update RosterEntries.
   */
  data: Prisma.XOR<Prisma.RosterEntryUpdateManyMutationInput, Prisma.RosterEntryUncheckedUpdateManyInput>
  /**
   * Filter which RosterEntries to update
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * Limit how many RosterEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RosterEntry upsert
 */
export type RosterEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the RosterEntry to update in case it exists.
   */
  where: Prisma.RosterEntryWhereUniqueInput
  /**
   * In case the RosterEntry found by the `where` argument doesn't exist, create a new RosterEntry with this data.
   */
  create: Prisma.XOR<Prisma.RosterEntryCreateInput, Prisma.RosterEntryUncheckedCreateInput>
  /**
   * In case the RosterEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RosterEntryUpdateInput, Prisma.RosterEntryUncheckedUpdateInput>
}

/**
 * RosterEntry delete
 */
export type RosterEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
  /**
   * Filter which RosterEntry to delete.
   */
  where: Prisma.RosterEntryWhereUniqueInput
}

/**
 * RosterEntry deleteMany
 */
export type RosterEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RosterEntries to delete
   */
  where?: Prisma.RosterEntryWhereInput
  /**
   * Limit how many RosterEntries to delete.
   */
  limit?: number
}

/**
 * RosterEntry without action
 */
export type RosterEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RosterEntry
   */
  select?: Prisma.RosterEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RosterEntry
   */
  omit?: Prisma.RosterEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RosterEntryInclude<ExtArgs> | null
}
