
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TeamStanding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TeamStanding
 * 
 */
export type TeamStandingModel = runtime.Types.Result.DefaultSelection<Prisma.$TeamStandingPayload>

export type AggregateTeamStanding = {
  _count: TeamStandingCountAggregateOutputType | null
  _avg: TeamStandingAvgAggregateOutputType | null
  _sum: TeamStandingSumAggregateOutputType | null
  _min: TeamStandingMinAggregateOutputType | null
  _max: TeamStandingMaxAggregateOutputType | null
}

export type TeamStandingAvgAggregateOutputType = {
  wins: number | null
  losses: number | null
  ties: number | null
  pointsFor: number | null
  pointsAgainst: number | null
  rank: number | null
}

export type TeamStandingSumAggregateOutputType = {
  wins: number | null
  losses: number | null
  ties: number | null
  pointsFor: number | null
  pointsAgainst: number | null
  rank: number | null
}

export type TeamStandingMinAggregateOutputType = {
  id: string | null
  teamId: string | null
  wins: number | null
  losses: number | null
  ties: number | null
  pointsFor: number | null
  pointsAgainst: number | null
  rank: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TeamStandingMaxAggregateOutputType = {
  id: string | null
  teamId: string | null
  wins: number | null
  losses: number | null
  ties: number | null
  pointsFor: number | null
  pointsAgainst: number | null
  rank: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TeamStandingCountAggregateOutputType = {
  id: number
  teamId: number
  wins: number
  losses: number
  ties: number
  pointsFor: number
  pointsAgainst: number
  rank: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TeamStandingAvgAggregateInputType = {
  wins?: true
  losses?: true
  ties?: true
  pointsFor?: true
  pointsAgainst?: true
  rank?: true
}

export type TeamStandingSumAggregateInputType = {
  wins?: true
  losses?: true
  ties?: true
  pointsFor?: true
  pointsAgainst?: true
  rank?: true
}

export type TeamStandingMinAggregateInputType = {
  id?: true
  teamId?: true
  wins?: true
  losses?: true
  ties?: true
  pointsFor?: true
  pointsAgainst?: true
  rank?: true
  createdAt?: true
  updatedAt?: true
}

export type TeamStandingMaxAggregateInputType = {
  id?: true
  teamId?: true
  wins?: true
  losses?: true
  ties?: true
  pointsFor?: true
  pointsAgainst?: true
  rank?: true
  createdAt?: true
  updatedAt?: true
}

export type TeamStandingCountAggregateInputType = {
  id?: true
  teamId?: true
  wins?: true
  losses?: true
  ties?: true
  pointsFor?: true
  pointsAgainst?: true
  rank?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TeamStandingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamStanding to aggregate.
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStandings to fetch.
   */
  orderBy?: Prisma.TeamStandingOrderByWithRelationInput | Prisma.TeamStandingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TeamStandingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStandings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStandings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TeamStandings
  **/
  _count?: true | TeamStandingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TeamStandingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TeamStandingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TeamStandingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TeamStandingMaxAggregateInputType
}

export type GetTeamStandingAggregateType<T extends TeamStandingAggregateArgs> = {
      [P in keyof T & keyof AggregateTeamStanding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTeamStanding[P]>
    : Prisma.GetScalarType<T[P], AggregateTeamStanding[P]>
}




export type TeamStandingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamStandingWhereInput
  orderBy?: Prisma.TeamStandingOrderByWithAggregationInput | Prisma.TeamStandingOrderByWithAggregationInput[]
  by: Prisma.TeamStandingScalarFieldEnum[] | Prisma.TeamStandingScalarFieldEnum
  having?: Prisma.TeamStandingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TeamStandingCountAggregateInputType | true
  _avg?: TeamStandingAvgAggregateInputType
  _sum?: TeamStandingSumAggregateInputType
  _min?: TeamStandingMinAggregateInputType
  _max?: TeamStandingMaxAggregateInputType
}

export type TeamStandingGroupByOutputType = {
  id: string
  teamId: string
  wins: number
  losses: number
  ties: number
  pointsFor: number | null
  pointsAgainst: number | null
  rank: number | null
  createdAt: Date
  updatedAt: Date
  _count: TeamStandingCountAggregateOutputType | null
  _avg: TeamStandingAvgAggregateOutputType | null
  _sum: TeamStandingSumAggregateOutputType | null
  _min: TeamStandingMinAggregateOutputType | null
  _max: TeamStandingMaxAggregateOutputType | null
}

type GetTeamStandingGroupByPayload<T extends TeamStandingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TeamStandingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TeamStandingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TeamStandingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TeamStandingGroupByOutputType[P]>
      }
    >
  >



export type TeamStandingWhereInput = {
  AND?: Prisma.TeamStandingWhereInput | Prisma.TeamStandingWhereInput[]
  OR?: Prisma.TeamStandingWhereInput[]
  NOT?: Prisma.TeamStandingWhereInput | Prisma.TeamStandingWhereInput[]
  id?: Prisma.StringFilter<"TeamStanding"> | string
  teamId?: Prisma.StringFilter<"TeamStanding"> | string
  wins?: Prisma.IntFilter<"TeamStanding"> | number
  losses?: Prisma.IntFilter<"TeamStanding"> | number
  ties?: Prisma.IntFilter<"TeamStanding"> | number
  pointsFor?: Prisma.FloatNullableFilter<"TeamStanding"> | number | null
  pointsAgainst?: Prisma.FloatNullableFilter<"TeamStanding"> | number | null
  rank?: Prisma.IntNullableFilter<"TeamStanding"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TeamStanding"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamStanding"> | Date | string
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}

export type TeamStandingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrderInput | Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrderInput | Prisma.SortOrder
  rank?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  team?: Prisma.TeamOrderByWithRelationInput
}

export type TeamStandingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  teamId?: string
  AND?: Prisma.TeamStandingWhereInput | Prisma.TeamStandingWhereInput[]
  OR?: Prisma.TeamStandingWhereInput[]
  NOT?: Prisma.TeamStandingWhereInput | Prisma.TeamStandingWhereInput[]
  wins?: Prisma.IntFilter<"TeamStanding"> | number
  losses?: Prisma.IntFilter<"TeamStanding"> | number
  ties?: Prisma.IntFilter<"TeamStanding"> | number
  pointsFor?: Prisma.FloatNullableFilter<"TeamStanding"> | number | null
  pointsAgainst?: Prisma.FloatNullableFilter<"TeamStanding"> | number | null
  rank?: Prisma.IntNullableFilter<"TeamStanding"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TeamStanding"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamStanding"> | Date | string
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}, "id" | "teamId">

export type TeamStandingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrderInput | Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrderInput | Prisma.SortOrder
  rank?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TeamStandingCountOrderByAggregateInput
  _avg?: Prisma.TeamStandingAvgOrderByAggregateInput
  _max?: Prisma.TeamStandingMaxOrderByAggregateInput
  _min?: Prisma.TeamStandingMinOrderByAggregateInput
  _sum?: Prisma.TeamStandingSumOrderByAggregateInput
}

export type TeamStandingScalarWhereWithAggregatesInput = {
  AND?: Prisma.TeamStandingScalarWhereWithAggregatesInput | Prisma.TeamStandingScalarWhereWithAggregatesInput[]
  OR?: Prisma.TeamStandingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TeamStandingScalarWhereWithAggregatesInput | Prisma.TeamStandingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TeamStanding"> | string
  teamId?: Prisma.StringWithAggregatesFilter<"TeamStanding"> | string
  wins?: Prisma.IntWithAggregatesFilter<"TeamStanding"> | number
  losses?: Prisma.IntWithAggregatesFilter<"TeamStanding"> | number
  ties?: Prisma.IntWithAggregatesFilter<"TeamStanding"> | number
  pointsFor?: Prisma.FloatNullableWithAggregatesFilter<"TeamStanding"> | number | null
  pointsAgainst?: Prisma.FloatNullableWithAggregatesFilter<"TeamStanding"> | number | null
  rank?: Prisma.IntNullableWithAggregatesFilter<"TeamStanding"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TeamStanding"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TeamStanding"> | Date | string
}

export type TeamStandingCreateInput = {
  id?: string
  wins?: number
  losses?: number
  ties?: number
  pointsFor?: number | null
  pointsAgainst?: number | null
  rank?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  team: Prisma.TeamCreateNestedOneWithoutStandingInput
}

export type TeamStandingUncheckedCreateInput = {
  id?: string
  teamId: string
  wins?: number
  losses?: number
  ties?: number
  pointsFor?: number | null
  pointsAgainst?: number | null
  rank?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TeamStandingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  ties?: Prisma.IntFieldUpdateOperationsInput | number
  pointsFor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pointsAgainst?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneRequiredWithoutStandingNestedInput
}

export type TeamStandingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  ties?: Prisma.IntFieldUpdateOperationsInput | number
  pointsFor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pointsAgainst?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamStandingCreateManyInput = {
  id?: string
  teamId: string
  wins?: number
  losses?: number
  ties?: number
  pointsFor?: number | null
  pointsAgainst?: number | null
  rank?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TeamStandingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  ties?: Prisma.IntFieldUpdateOperationsInput | number
  pointsFor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pointsAgainst?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamStandingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  ties?: Prisma.IntFieldUpdateOperationsInput | number
  pointsFor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pointsAgainst?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamStandingNullableScalarRelationFilter = {
  is?: Prisma.TeamStandingWhereInput | null
  isNot?: Prisma.TeamStandingWhereInput | null
}

export type TeamStandingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TeamStandingAvgOrderByAggregateInput = {
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type TeamStandingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TeamStandingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TeamStandingSumOrderByAggregateInput = {
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  ties?: Prisma.SortOrder
  pointsFor?: Prisma.SortOrder
  pointsAgainst?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type TeamStandingCreateNestedOneWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamStandingCreateWithoutTeamInput, Prisma.TeamStandingUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamStandingCreateOrConnectWithoutTeamInput
  connect?: Prisma.TeamStandingWhereUniqueInput
}

export type TeamStandingUncheckedCreateNestedOneWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamStandingCreateWithoutTeamInput, Prisma.TeamStandingUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamStandingCreateOrConnectWithoutTeamInput
  connect?: Prisma.TeamStandingWhereUniqueInput
}

export type TeamStandingUpdateOneWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStandingCreateWithoutTeamInput, Prisma.TeamStandingUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamStandingCreateOrConnectWithoutTeamInput
  upsert?: Prisma.TeamStandingUpsertWithoutTeamInput
  disconnect?: Prisma.TeamStandingWhereInput | boolean
  delete?: Prisma.TeamStandingWhereInput | boolean
  connect?: Prisma.TeamStandingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TeamStandingUpdateToOneWithWhereWithoutTeamInput, Prisma.TeamStandingUpdateWithoutTeamInput>, Prisma.TeamStandingUncheckedUpdateWithoutTeamInput>
}

export type TeamStandingUncheckedUpdateOneWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStandingCreateWithoutTeamInput, Prisma.TeamStandingUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamStandingCreateOrConnectWithoutTeamInput
  upsert?: Prisma.TeamStandingUpsertWithoutTeamInput
  disconnect?: Prisma.TeamStandingWhereInput | boolean
  delete?: Prisma.TeamStandingWhereInput | boolean
  connect?: Prisma.TeamStandingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TeamStandingUpdateToOneWithWhereWithoutTeamInput, Prisma.TeamStandingUpdateWithoutTeamInput>, Prisma.TeamStandingUncheckedUpdateWithoutTeamInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TeamStandingCreateWithoutTeamInput = {
  id?: string
  wins?: number
  losses?: number
  ties?: number
  pointsFor?: number | null
  pointsAgainst?: number | null
  rank?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TeamStandingUncheckedCreateWithoutTeamInput = {
  id?: string
  wins?: number
  losses?: number
  ties?: number
  pointsFor?: number | null
  pointsAgainst?: number | null
  rank?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TeamStandingCreateOrConnectWithoutTeamInput = {
  where: Prisma.TeamStandingWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamStandingCreateWithoutTeamInput, Prisma.TeamStandingUncheckedCreateWithoutTeamInput>
}

export type TeamStandingUpsertWithoutTeamInput = {
  update: Prisma.XOR<Prisma.TeamStandingUpdateWithoutTeamInput, Prisma.TeamStandingUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.TeamStandingCreateWithoutTeamInput, Prisma.TeamStandingUncheckedCreateWithoutTeamInput>
  where?: Prisma.TeamStandingWhereInput
}

export type TeamStandingUpdateToOneWithWhereWithoutTeamInput = {
  where?: Prisma.TeamStandingWhereInput
  data: Prisma.XOR<Prisma.TeamStandingUpdateWithoutTeamInput, Prisma.TeamStandingUncheckedUpdateWithoutTeamInput>
}

export type TeamStandingUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  ties?: Prisma.IntFieldUpdateOperationsInput | number
  pointsFor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pointsAgainst?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamStandingUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  ties?: Prisma.IntFieldUpdateOperationsInput | number
  pointsFor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pointsAgainst?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TeamStandingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  wins?: boolean
  losses?: boolean
  ties?: boolean
  pointsFor?: boolean
  pointsAgainst?: boolean
  rank?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamStanding"]>

export type TeamStandingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  wins?: boolean
  losses?: boolean
  ties?: boolean
  pointsFor?: boolean
  pointsAgainst?: boolean
  rank?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamStanding"]>

export type TeamStandingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  wins?: boolean
  losses?: boolean
  ties?: boolean
  pointsFor?: boolean
  pointsAgainst?: boolean
  rank?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamStanding"]>

export type TeamStandingSelectScalar = {
  id?: boolean
  teamId?: boolean
  wins?: boolean
  losses?: boolean
  ties?: boolean
  pointsFor?: boolean
  pointsAgainst?: boolean
  rank?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TeamStandingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "teamId" | "wins" | "losses" | "ties" | "pointsFor" | "pointsAgainst" | "rank" | "createdAt" | "updatedAt", ExtArgs["result"]["teamStanding"]>
export type TeamStandingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type TeamStandingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type TeamStandingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}

export type $TeamStandingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TeamStanding"
  objects: {
    team: Prisma.$TeamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    teamId: string
    wins: number
    losses: number
    ties: number
    pointsFor: number | null
    pointsAgainst: number | null
    rank: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["teamStanding"]>
  composites: {}
}

export type TeamStandingGetPayload<S extends boolean | null | undefined | TeamStandingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload, S>

export type TeamStandingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TeamStandingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TeamStandingCountAggregateInputType | true
  }

export interface TeamStandingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TeamStanding'], meta: { name: 'TeamStanding' } }
  /**
   * Find zero or one TeamStanding that matches the filter.
   * @param {TeamStandingFindUniqueArgs} args - Arguments to find a TeamStanding
   * @example
   * // Get one TeamStanding
   * const teamStanding = await prisma.teamStanding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TeamStandingFindUniqueArgs>(args: Prisma.SelectSubset<T, TeamStandingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TeamStanding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TeamStandingFindUniqueOrThrowArgs} args - Arguments to find a TeamStanding
   * @example
   * // Get one TeamStanding
   * const teamStanding = await prisma.teamStanding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TeamStandingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TeamStandingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamStanding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingFindFirstArgs} args - Arguments to find a TeamStanding
   * @example
   * // Get one TeamStanding
   * const teamStanding = await prisma.teamStanding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TeamStandingFindFirstArgs>(args?: Prisma.SelectSubset<T, TeamStandingFindFirstArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamStanding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingFindFirstOrThrowArgs} args - Arguments to find a TeamStanding
   * @example
   * // Get one TeamStanding
   * const teamStanding = await prisma.teamStanding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TeamStandingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TeamStandingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TeamStandings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TeamStandings
   * const teamStandings = await prisma.teamStanding.findMany()
   * 
   * // Get first 10 TeamStandings
   * const teamStandings = await prisma.teamStanding.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const teamStandingWithIdOnly = await prisma.teamStanding.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TeamStandingFindManyArgs>(args?: Prisma.SelectSubset<T, TeamStandingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TeamStanding.
   * @param {TeamStandingCreateArgs} args - Arguments to create a TeamStanding.
   * @example
   * // Create one TeamStanding
   * const TeamStanding = await prisma.teamStanding.create({
   *   data: {
   *     // ... data to create a TeamStanding
   *   }
   * })
   * 
   */
  create<T extends TeamStandingCreateArgs>(args: Prisma.SelectSubset<T, TeamStandingCreateArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TeamStandings.
   * @param {TeamStandingCreateManyArgs} args - Arguments to create many TeamStandings.
   * @example
   * // Create many TeamStandings
   * const teamStanding = await prisma.teamStanding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TeamStandingCreateManyArgs>(args?: Prisma.SelectSubset<T, TeamStandingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TeamStandings and returns the data saved in the database.
   * @param {TeamStandingCreateManyAndReturnArgs} args - Arguments to create many TeamStandings.
   * @example
   * // Create many TeamStandings
   * const teamStanding = await prisma.teamStanding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TeamStandings and only return the `id`
   * const teamStandingWithIdOnly = await prisma.teamStanding.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TeamStandingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TeamStandingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TeamStanding.
   * @param {TeamStandingDeleteArgs} args - Arguments to delete one TeamStanding.
   * @example
   * // Delete one TeamStanding
   * const TeamStanding = await prisma.teamStanding.delete({
   *   where: {
   *     // ... filter to delete one TeamStanding
   *   }
   * })
   * 
   */
  delete<T extends TeamStandingDeleteArgs>(args: Prisma.SelectSubset<T, TeamStandingDeleteArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TeamStanding.
   * @param {TeamStandingUpdateArgs} args - Arguments to update one TeamStanding.
   * @example
   * // Update one TeamStanding
   * const teamStanding = await prisma.teamStanding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TeamStandingUpdateArgs>(args: Prisma.SelectSubset<T, TeamStandingUpdateArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TeamStandings.
   * @param {TeamStandingDeleteManyArgs} args - Arguments to filter TeamStandings to delete.
   * @example
   * // Delete a few TeamStandings
   * const { count } = await prisma.teamStanding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TeamStandingDeleteManyArgs>(args?: Prisma.SelectSubset<T, TeamStandingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamStandings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TeamStandings
   * const teamStanding = await prisma.teamStanding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TeamStandingUpdateManyArgs>(args: Prisma.SelectSubset<T, TeamStandingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamStandings and returns the data updated in the database.
   * @param {TeamStandingUpdateManyAndReturnArgs} args - Arguments to update many TeamStandings.
   * @example
   * // Update many TeamStandings
   * const teamStanding = await prisma.teamStanding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TeamStandings and only return the `id`
   * const teamStandingWithIdOnly = await prisma.teamStanding.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TeamStandingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TeamStandingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TeamStanding.
   * @param {TeamStandingUpsertArgs} args - Arguments to update or create a TeamStanding.
   * @example
   * // Update or create a TeamStanding
   * const teamStanding = await prisma.teamStanding.upsert({
   *   create: {
   *     // ... data to create a TeamStanding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TeamStanding we want to update
   *   }
   * })
   */
  upsert<T extends TeamStandingUpsertArgs>(args: Prisma.SelectSubset<T, TeamStandingUpsertArgs<ExtArgs>>): Prisma.Prisma__TeamStandingClient<runtime.Types.Result.GetResult<Prisma.$TeamStandingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TeamStandings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingCountArgs} args - Arguments to filter TeamStandings to count.
   * @example
   * // Count the number of TeamStandings
   * const count = await prisma.teamStanding.count({
   *   where: {
   *     // ... the filter for the TeamStandings we want to count
   *   }
   * })
  **/
  count<T extends TeamStandingCountArgs>(
    args?: Prisma.Subset<T, TeamStandingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TeamStandingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TeamStanding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TeamStandingAggregateArgs>(args: Prisma.Subset<T, TeamStandingAggregateArgs>): Prisma.PrismaPromise<GetTeamStandingAggregateType<T>>

  /**
   * Group by TeamStanding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStandingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TeamStandingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TeamStandingGroupByArgs['orderBy'] }
      : { orderBy?: TeamStandingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TeamStandingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTeamStandingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TeamStanding model
 */
readonly fields: TeamStandingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TeamStanding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TeamStandingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TeamStanding model
 */
export interface TeamStandingFieldRefs {
  readonly id: Prisma.FieldRef<"TeamStanding", 'String'>
  readonly teamId: Prisma.FieldRef<"TeamStanding", 'String'>
  readonly wins: Prisma.FieldRef<"TeamStanding", 'Int'>
  readonly losses: Prisma.FieldRef<"TeamStanding", 'Int'>
  readonly ties: Prisma.FieldRef<"TeamStanding", 'Int'>
  readonly pointsFor: Prisma.FieldRef<"TeamStanding", 'Float'>
  readonly pointsAgainst: Prisma.FieldRef<"TeamStanding", 'Float'>
  readonly rank: Prisma.FieldRef<"TeamStanding", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TeamStanding", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TeamStanding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TeamStanding findUnique
 */
export type TeamStandingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * Filter, which TeamStanding to fetch.
   */
  where: Prisma.TeamStandingWhereUniqueInput
}

/**
 * TeamStanding findUniqueOrThrow
 */
export type TeamStandingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * Filter, which TeamStanding to fetch.
   */
  where: Prisma.TeamStandingWhereUniqueInput
}

/**
 * TeamStanding findFirst
 */
export type TeamStandingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * Filter, which TeamStanding to fetch.
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStandings to fetch.
   */
  orderBy?: Prisma.TeamStandingOrderByWithRelationInput | Prisma.TeamStandingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamStandings.
   */
  cursor?: Prisma.TeamStandingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStandings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStandings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamStandings.
   */
  distinct?: Prisma.TeamStandingScalarFieldEnum | Prisma.TeamStandingScalarFieldEnum[]
}

/**
 * TeamStanding findFirstOrThrow
 */
export type TeamStandingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * Filter, which TeamStanding to fetch.
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStandings to fetch.
   */
  orderBy?: Prisma.TeamStandingOrderByWithRelationInput | Prisma.TeamStandingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamStandings.
   */
  cursor?: Prisma.TeamStandingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStandings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStandings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamStandings.
   */
  distinct?: Prisma.TeamStandingScalarFieldEnum | Prisma.TeamStandingScalarFieldEnum[]
}

/**
 * TeamStanding findMany
 */
export type TeamStandingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * Filter, which TeamStandings to fetch.
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStandings to fetch.
   */
  orderBy?: Prisma.TeamStandingOrderByWithRelationInput | Prisma.TeamStandingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TeamStandings.
   */
  cursor?: Prisma.TeamStandingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStandings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStandings.
   */
  skip?: number
  distinct?: Prisma.TeamStandingScalarFieldEnum | Prisma.TeamStandingScalarFieldEnum[]
}

/**
 * TeamStanding create
 */
export type TeamStandingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * The data needed to create a TeamStanding.
   */
  data: Prisma.XOR<Prisma.TeamStandingCreateInput, Prisma.TeamStandingUncheckedCreateInput>
}

/**
 * TeamStanding createMany
 */
export type TeamStandingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TeamStandings.
   */
  data: Prisma.TeamStandingCreateManyInput | Prisma.TeamStandingCreateManyInput[]
}

/**
 * TeamStanding createManyAndReturn
 */
export type TeamStandingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * The data used to create many TeamStandings.
   */
  data: Prisma.TeamStandingCreateManyInput | Prisma.TeamStandingCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TeamStanding update
 */
export type TeamStandingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * The data needed to update a TeamStanding.
   */
  data: Prisma.XOR<Prisma.TeamStandingUpdateInput, Prisma.TeamStandingUncheckedUpdateInput>
  /**
   * Choose, which TeamStanding to update.
   */
  where: Prisma.TeamStandingWhereUniqueInput
}

/**
 * TeamStanding updateMany
 */
export type TeamStandingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TeamStandings.
   */
  data: Prisma.XOR<Prisma.TeamStandingUpdateManyMutationInput, Prisma.TeamStandingUncheckedUpdateManyInput>
  /**
   * Filter which TeamStandings to update
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * Limit how many TeamStandings to update.
   */
  limit?: number
}

/**
 * TeamStanding updateManyAndReturn
 */
export type TeamStandingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * The data used to update TeamStandings.
   */
  data: Prisma.XOR<Prisma.TeamStandingUpdateManyMutationInput, Prisma.TeamStandingUncheckedUpdateManyInput>
  /**
   * Filter which TeamStandings to update
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * Limit how many TeamStandings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TeamStanding upsert
 */
export type TeamStandingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * The filter to search for the TeamStanding to update in case it exists.
   */
  where: Prisma.TeamStandingWhereUniqueInput
  /**
   * In case the TeamStanding found by the `where` argument doesn't exist, create a new TeamStanding with this data.
   */
  create: Prisma.XOR<Prisma.TeamStandingCreateInput, Prisma.TeamStandingUncheckedCreateInput>
  /**
   * In case the TeamStanding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TeamStandingUpdateInput, Prisma.TeamStandingUncheckedUpdateInput>
}

/**
 * TeamStanding delete
 */
export type TeamStandingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
  /**
   * Filter which TeamStanding to delete.
   */
  where: Prisma.TeamStandingWhereUniqueInput
}

/**
 * TeamStanding deleteMany
 */
export type TeamStandingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamStandings to delete
   */
  where?: Prisma.TeamStandingWhereInput
  /**
   * Limit how many TeamStandings to delete.
   */
  limit?: number
}

/**
 * TeamStanding without action
 */
export type TeamStandingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStanding
   */
  select?: Prisma.TeamStandingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStanding
   */
  omit?: Prisma.TeamStandingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStandingInclude<ExtArgs> | null
}
